name       : rygel
version    : '45.0'
release    : 30
source     :
    - https://download.gnome.org/sources/rygel/45/rygel-45.0.tar.xz : 82667b902fc0672e64cf91eb727a70137a8fdfe7a3d9a4c158b0f4b1fc700882
homepage   : https://gnome.pages.gitlab.gnome.org/rygel/
license    : LGPL-2.0-or-later
component  : network.util
summary    : Rygel uPnP Media Server
description: |
    Rygel is a home media solution that allows you to easily share audio, video and pictures, and control of media player on your home network. In technical terms it is both a UPnP AV MediaServer and MediaRenderer implemented through a plug-in mechanism. Interoperability with other devices in the market is achieved by conformance to very strict requirements of DLNA and on the fly conversion of media to format that client devices are capable of handling.
optimize   :
    - lto
builddeps  :
    - pkgconfig(gee-0.8)
    - pkgconfig(gst-editing-services-1.0)
    - pkgconfig(gtk4)
    - pkgconfig(gupnp-1.6)
    - pkgconfig(gupnp-av-1.0)
    - pkgconfig(gupnp-dlna-2.0)
    - pkgconfig(libmediaart-2.0)
    - pkgconfig(tinysparql-3.0)
    - gtk-doc
    - libunistring-devel
    - valadoc
setup      : |
    %patch -p1 -i $pkgfiles/0001-solus-Make-stateless.patch
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
