name       : gnome-calendar
version    : 49.0.1
release    : 51
source     :
    - https://download.gnome.org/sources/gnome-calendar/49/gnome-calendar-49.0.1.tar.xz : e0bfe4ea109422dada0745dd8f8c0e0230ab88207710d1c07e245322cf913ff2
homepage   : https://apps.gnome.org/Calendar/
license    : GPL-3.0-or-later
component  : office
summary    : Manage your schedule
description: |
    GNOME Calendar is an elegant tool to help you plan and stay on top of your schedule for upcoming days and weeks, whether your months are filled with meetings and appointments, public events, travel logistics, or other commitments in your life. Easily create and manage unlimited calendars and events with GNOME Calendar's infinite scrolling month view, week timetable, and scheduling list view. Integrating the latest GNOME technologies and design best practices, GNOME Calendar builds on top of the mature Evolution data server to manage large quantities of events and to provide integration with other applications. You can add calendars from various online calendaring services (like NextCloud, Google Calendar, and CalDAV / WebDAV servers), enabling you to synchronize your events across multiple devices and platforms. GNOME Calendar also supports local and offline calendaring, so you can use it anywhere and anytime while travelling (or after civilization's collapse.)
builddeps  :
    - pkgconfig(goa-1.0)
    - pkgconfig(gsettings-desktop-schemas)
    - pkgconfig(gtk4)
    - pkgconfig(gweather4)
    - pkgconfig(libadwaita-1)
    - pkgconfig(libdazzle-1.0)
    - pkgconfig(libecal-2.0)
    - pkgconfig(libgeoclue-2.0)
    - pkgconfig(libical)
    - pkgconfig(libsecret-1)
    - pkgconfig(libsoup-3.0)
    - blueprint-compiler
setup      : |
    %patch -p1 -i $pkgfiles/0001-Fix-missing-MimeType-handler-for-Calendar.patch
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
