name       : python-astroid
version    : 3.3.11
release    : 40
source     :
    - https://github.com/pylint-dev/astroid/archive/v3.3.11/astroid-3.3.11.tar.gz : 5bb714e739c650e7e31186e1765f7edd33171b2f423ddbddb43b1c37cb6cfbb5
homepage   : https://github.com/PyCQA/astroid
license    : LGPL-2.1-or-later
component  : programming.python
summary    : A common base representation of python source code for pylint and other projects
description: |
    The aim of this module is to provide a common base representation of python source code. It is currently the library powering pylint's capabilities.
builddeps  :
    - python-build
    - python-installer
    - python-setuptools
    - python-wheel
checkdeps  :
    - numpy
    - python-attrs
    - python-dateutil
    - python-mypy
    - python-pytest
    - python-regex
    - python-typing-extensions
    - python-urllib3
rundeps    :
    - python-typing-extensions
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    numpy_test_prefix=tests/brain/numpy
    pytest_args=(
        # Numpy failures likely present since Numpy 2.0:
        # https://github.com/pylint-dev/astroid/issues/2442
        --deselect "${numpy_test_prefix}/test_core_einsumfunc.py::test_numpy_function_calls_inferred_as_ndarray"
        --deselect "${numpy_test_prefix}/test_core_fromnumeric.py::BrainNumpyCoreFromNumericTest::test_numpy_function_calls_inferred_as_ndarray"
        --deselect "${numpy_test_prefix}/test_core_multiarray.py::BrainNumpyCoreMultiarrayTest::test_numpy_function_calls_inferred_as_ndarray"
        --deselect "${numpy_test_prefix}/test_core_numerictypes.py::NumpyBrainCoreNumericTypesTest::test_datetime_astype_return"
        --deselect "${numpy_test_prefix}/test_core_numerictypes.py::NumpyBrainCoreNumericTypesTest::test_generic_types_are_subscriptables"
        --deselect "${numpy_test_prefix}/test_core_umath.py::NumpyBrainCoreUmathTest::test_numpy_core_umath_functions_return_type"
        --deselect "${numpy_test_prefix}/test_core_umath.py::NumpyBrainCoreUmathTest::test_numpy_core_umath_functions_return_type_tuple"
        # Setuptools warning causing test failure:
        # https://github.com/pylint-dev/astroid/issues/2759
        --deselect tests/test_manager.py::AstroidManagerTest::test_identify_old_namespace_package_protocol
    )

    %python3_test pytest -v "${pytest_args[@]}"
