name       : python-iniconfig
version    : 2.1.0
release    : 6
source     :
    - https://files.pythonhosted.org/packages/source/i/iniconfig/iniconfig-2.1.0.tar.gz : 3abbd2e30b36733fee78f9c7f7308f2d0050e88f0087fd25c2645f63c773e1c7
homepage   : https://github.com/pytest-dev/iniconfig
license    : MIT
component  : programming.python
summary    : brain-dead simple config-ini parsing
description: |
    iniconfig is a small and simple INI-file parser module having a unique set of features.
builddeps  :
    - python-build
    - python-hatch-vcs
    - python-installer
    - python-packaging
build      : |
    %python3_setup
install    : |
    %python3_install
