name       : python-kiwisolver
version    : 1.4.9
release    : 13
source     :
    - https://files.pythonhosted.org/packages/source/k/kiwisolver/kiwisolver-1.4.9.tar.gz : c3b22c26c6fd6811b0ae8363b95ca8ce4ea3c202d3d0975b2914310ceb1bcc4d
homepage   : https://github.com/nucleic/kiwi
license    : BSD-3-Clause
component  : programming.python
summary    : An efficient C++ implementation of the Cassowary constraint solving algorithm
description: |
    Kiwi is an implementation of the algorithm based on the seminal Cassowary paper. It is not a refactoring of the original C++ solver. Kiwi has been designed from the ground up to be lightweight and fast. Kiwi ranges from 10x to 500x faster than the original Cassowary solver with typical use cases gaining a 40x improvement. Memory savings are consistently > 5x.
builddeps  :
    - pkgconfig(python3)
    - python-build
    - python-cppy
    - python-installer
    - python-setuptools
    - python-setuptools-scm
checkdeps  :
    - python-pytest
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest3
