name       : gnome-chess
version    : '49.0'
release    : 38
source     :
    - https://download.gnome.org/sources/gnome-chess/49/gnome-chess-49.0.tar.xz : 403493f016e9927d7f9c54773bbc9d0a9341f3eef9d4317b45edc0ab0a22c88f
homepage   : https://gitlab.gnome.org/GNOME/gnome-chess
license    : GPL-2.0-or-later
component  : games.strategy
summary    : GNOME Chess Game
description: |
    GNOME Chess is a 2D chess game, where games can be played between a combination of human and computer players. GNOME Chess detects known third party chess engines for computer players.
optimize   :
    - lto
builddeps  :
    - pkgconfig(glu)
    - pkgconfig(libadwaita-1)
    - pkgconfig(librsvg-2.0)
    - desktop-file-utils
    - itstool
    - vala
rundeps    :
    - gnuchess
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
