name       : libdex
version    : 1.0.0
release    : 11
source     :
    - https://download.gnome.org/sources/libdex/1.0/libdex-1.0.0.tar.xz : 7b8f5c5db3796e14e12e10422e2356766ba830b92815fee70bbc867b5b207f5d
homepage   : https://gitlab.gnome.org/GNOME/libdex
license    : LGPL-2.1-or-later
component  : programming.library
summary    : A library supporting Deferred Execution
description: |
    Dex provides Future-based programming for GLib-based applications. It both integrates with and brings new features for application and library authors who want to structure concurrent code in an easy to manage way. Dex also provides Fibers which allow writing synchronous looking code in C that uses asynchronous and future-based APIs.
optimize   :
    - lto
builddeps  :
    - pkgconfig(liburing)
    - pkgconfig(sysprof-capture-4)
    - gi-docgen
    - vala
setup      : |
    %patch -p1 -R -i $pkgfiles/meson-shenanigans.patch
    %meson_configure -Dsysprof=true -Ddocs=true -Dexamples=false
build      : |
    %ninja_build
install    : |
    %ninja_install
patterns   :
    - docs :
        - /usr/share/doc/libdex-1
