name       : gnome-console
version    : '49.0'
release    : 7
source     :
    - https://download.gnome.org/sources/gnome-console/49/gnome-console-49.0.tar.xz : 9e8e9646f473d01f4b4a7bce2c47ad226b4ae83fabf24cbbb4ac94f6ac5d5cc2
homepage   : https://apps.gnome.org/Console/
license    : GPL-3.0-or-later
component  : desktop.gnome
summary    : Terminal Emulator
description: |
    A simple user-friendly terminal emulator for the GNOME desktop
optimize   :
    - lto
builddeps  :
    - pkgconfig(gsettings-desktop-schemas)
    - pkgconfig(libadwaita-1)
    - pkgconfig(libgtop-2.0)
    - pkgconfig(vte-2.91-gtk4)
    - desktop-file-utils
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
