name       : open-vm-tools
version    : 12.4.0
release    : 325
source     :
    - https://github.com/vmware/open-vm-tools/archive/stable-12.4.0.tar.gz : ba091c58f0d61c2896418c7d04506a7ea44c7594401209928270576fa018c23a
license    : LGPL-2.1-or-later
component  : system.utils
homepage   : https://github.com/vmware/open-vm-tools
summary    :
    - open-vm-tools is a set of services and modules that enable several features in VMware products
    - modaliases : These files are used by the Software Center for hardware detection.
description: |
    open-vm-tools is a set of services and modules that enable several features in VMware products
builddeps  :
    - pkgconfig(fuse)
    - pkgconfig(gdk-pixbuf-xlib-2.0)
    - pkgconfig(gtkmm-3.0)
    - pkgconfig(libdrm)
    - pkgconfig(libmspack)
    - pkgconfig(libproc2)
    - pkgconfig(libtirpc)
    - pkgconfig(sm)
    - pkgconfig(xext)
    - pkgconfig(xi)
    - pkgconfig(xinerama)
    - pkgconfig(xmlsec1)
    - pkgconfig(xrandr)
    - pkgconfig(xrender)
    - pkgconfig(xtst)
    - linux-current-headers
    - rpcsvc-proto-devel
patterns   :
    - modaliases : /usr/share/linux-driver-management/modaliases
optimize   : no-bind-now
setup      : |
    pushd open-vm-tools
    %patch -p1 -i $pkgfiles/0001-Don-t-set-Werror-it-s-evil.patch
    sed -i -e 's|.*common-agent/etc/config/Makefile.*||' configure.ac
    mkdir -p common-agent/etc/config
    %reconfigure --with-kernel-release="%kernel_version_current%" \
                 --with-gtk3 \
                 --with-gtkmm3 \
                 --disable-static
build      : |
    pushd open-vm-tools
    %make
install    : |
    pushd open-vm-tools
    %make_install
    install -Dm00644 $pkgfiles/vmtoolsd.service $installdir/%libdir%/systemd/system/vmtoolsd.service

    # Let LDM know about our aliases
    install -Dm00644 $pkgfiles/open-vm-tools.modaliases $installdir/usr/share/linux-driver-management/modaliases/open-vm-tools.modaliases

    # Overwrite PAM config
    rm -v $installdir/etc/pam.d/vmtoolsd
    install -Dm00644 $pkgfiles/vmtoolsd.pam $installdir/usr/share/defaults/etc/pam.d/vmtoolsd

    # Stateless spot for it
    install -Ddm00755 $installdir/usr/share/xdg/autostart/
    mv $installdir/etc/xdg/autostart/* $installdir/usr/share/xdg/autostart/

    # Cleanup
    find $installdir -type d -empty -print -delete
