name       : breezy
version    : 3.3.12
release    : 1
source     :
    - https://launchpad.net/brz/3.3/3.3.12/+download/breezy-3.3.12.tar.gz : 11cb9c5e2fac2038630e863088f047eade4653cbf2b995f732322f6c143bbb3b
homepage   : https://www.breezy-vcs.org/
license    : GPL-2.0-or-later
component  : programming.tools
summary    : Breezy is a friendly powerful distributed version control system.
description: |
    Breezy is a version control system implemented in Python with multi-format support and an emphasis on hackability.
networking : yes
builddeps  :
    - pkgconfig(python3)
    - cython
    - pip
    - python-build
    - python-installer
    - python-setuptools-rust
    - python-wheel
environment: |
    export CFLAGS="${CFLAGS} -Wno-implicit-function-declaration"
build      : |
    export PYTHONUSERBASE=$workdir
    export PATH=$PATH:$workdir/bin/
    python3 -m pip install --user setuptools-gettext

    %python3_setup
install    : |
    %python3_install

    rm -fr $installdir/usr/lib/python%python3_version%/site-packages/breezy/tests/
replaces   :
    - bzr
