name       : thunar-media-tags-plugin
version    : 0.5.0
release    : 3
source     :
    - https://archive.xfce.org/src/thunar-plugins/thunar-media-tags-plugin/0.5/thunar-media-tags-plugin-0.5.0.tar.bz2 : 105a72d51c7fbcc690c9b9a850f3743accbd9bf5dc51480b5ea283dfde96d61e
homepage   : https://docs.xfce.org/xfce/thunar/media-tags
license    : GPL-2.0-or-later
component  : desktop.xfce
summary    : Adds special features for media files to the Thunar File Manager.
description: |
    Adds special features for media files to the Thunar File Manager.
builddeps  :
    - pkgconfig(exo-2)
    - pkgconfig(taglib)
    - pkgconfig(thunarx-3)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
