name       : baobab
version    : '49.0'
release    : 31
source     :
    - https://download.gnome.org/sources/baobab/49/baobab-49.0.tar.xz : 195c0182dc4d7f694dd0b4ee36e72e0f4ab757825fc238233409eec2df483fae
homepage   : https://apps.gnome.org/Baobab/
license    : GPL-2.0-or-later
component  : desktop.gnome
summary    : Check folder sizes and available disk space
description: |
    A simple application to keep your disk usage and available space under control. Disk Usage Analyzer can scan specific folders, storage devices and online accounts. It provides both a tree and a graphical representation showing the size of each folder, making it easy to identify where disk space is wasted.
optimize   :
    - lto
builddeps  :
    - pkgconfig(gtk4)
    - pkgconfig(libadwaita-1)
    - desktop-file-utils
    - itstool
    - vala
setup      : |
    %patch -p1 -i $pkgfiles/0001-Stop-registering-mimetype-to-open-directories.patch
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
