name       : glycin
version    : 2.0.0
release    : 8
source     :
    - https://download.gnome.org/sources/glycin/2.0/glycin-2.0.0.tar.xz : e39c3ca4f5bd6905f19f090456940650c8de1f217d2edb1f46ee17e04e7ae502
homepage   : https://gitlab.gnome.org/sophie-h/glycin
license    :
    - LGPL-2.1-or-later
    - MPL-2.0
component  : desktop.gnome
summary    : Sandboxed and extendable image decoding
description: |
    Glycin allows to decode images into gdk::Texture(s) and to extract image metadata. The decoding happens in sandboxed modular image loaders.
clang      : true
networking : true
builddeps  :
    - pkgconfig(cairo)
    - pkgconfig(gtk4)
    - pkgconfig(lcms2)
    - pkgconfig(libheif)
    - pkgconfig(libjxl)
    - pkgconfig(librsvg-2.0)
    - pkgconfig(libseccomp)
    - pkgconfig(libxml-2.0)
    - git
    - rust
    - vala
setup      : |
    %meson_configure -Dtest_skip_install=true
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    # It always failed
    # %ninja_check
patterns   :
    - gtk4 :
        - /usr/lib64/girepository-1.0/GlyGtk4-*
        - /usr/lib64/libglycin-gtk4-2.so.*
    - gtk4-devel :
        - /usr/include/glycin-gtk4-*
        - /usr/lib64/libglycin-gtk4-2.so
        - /usr/lib64/pkgconfig/glycin-gtk4-*
        - /usr/share/gir-1.0/GlyGtk4-*
        - /usr/share/vala/vapi/glycin-gtk4-*
