name       : gsettings-desktop-schemas
version    : '49.0'
release    : 64
source     :
    - https://download.gnome.org/sources/gsettings-desktop-schemas/49/gsettings-desktop-schemas-49.0.tar.xz : 912905cc45382888a47702ed1101c6b08ebd0122a32a67d940ab8116a96c520d
homepage   : https://gitlab.gnome.org/GNOME/gsettings-desktop-schemas
license    : LGPL-2.1-or-later
component  : desktop.gnome.core
summary    : A collection of GSettings schemas for settings shared by various components of a GNOME Desktop.
description: |
    A collection of GSettings schemas for settings shared by various components of a GNOME Desktop.
builddeps  :
    - pkgconfig(gobject-introspection-1.0)
patterns   :
    - devel : /usr/share/pkgconfig
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
