name       : mlt
version    : 7.28.0
release    : 46
source     :
    - https://github.com/mltframework/mlt/releases/download/v7.28.0/mlt-7.28.0.tar.gz : bc425bf9602213f5f4855b78cfbbcd43eeb78097c508588bde44415963955aa1
homepage   : https://www.mltframework.org/
license    :
    - GPL-2.0-or-later
    - GPL-3.0-or-later
    - LGPL-2.1-or-later
component  : multimedia.library
summary    : Multimedia framework designed for television broadcasting.
description: |
    Multimedia framework designed for television broadcasting.
patterns   :
    - python :
        - /usr/lib/python3.*/site-packages/*
builddeps  :
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt6Core5Compat)
    - pkgconfig(Qt6Svg)
    - pkgconfig(SDL2_image)
    - pkgconfig(alsa)
    - pkgconfig(fftw3)
    - pkgconfig(frei0r)
    - pkgconfig(gl)
    - pkgconfig(libarchive)
    - pkgconfig(libavformat)
    - pkgconfig(libexif)
    - pkgconfig(libpulse)
    - pkgconfig(movit)
    - pkgconfig(opencv4)
    - pkgconfig(python3)
    - pkgconfig(samplerate)
    - pkgconfig(vidstab)
    - pkgconfig(x11)
    - swig
rundeps    :
    - frei0r
setup      : |
    %cmake_ninja \
        -DMOD_GDK=OFF \
        -DMOD_GLAXNIMATE=ON \
        -DMOD_GLAXNIMATE_QT6=ON \
        -DMOD_OPENCV=ON \
        -DMOD_QT6=ON \
        -DSWIG_PYTHON=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
