name       : libpeas-2
version    : 2.2.0
release    : 11
source     :
    - https://download.gnome.org/sources/libpeas/2.2/libpeas-2.2.0.tar.xz : c2887233f084a69fabfc7fa0140d410491863d7050afb28677f9a553b2580ad9
homepage   : https://gnome.pages.gitlab.gnome.org/libpeas/libpeas-2/
license    : LGPL-2.1-or-later
component  : desktop.gnome.core
summary    : libpeas provides a plugin framework for GLib applications
description: |
    libpeas is a gobject-based plugins engine, and is targetted at giving every application the chance to assume its own extensibility.
optimize   :
    - lto
builddeps  :
    - pkgconfig(gjs-1.0)
    - pkgconfig(pygobject-3.0)
    - pkgconfig(python3)
    - python-setuptools
    - vala
rundeps    :
    - python-gobject
setup      : |
    %meson_configure -Dlua51=false -Dvapi=true
build      : |
    %ninja_build
install    : |
    %ninja_install
