name       : python-gobject
version    : 3.54.2
release    : 42
source     :
    - https://download.gnome.org/sources/pygobject/3.54/pygobject-3.54.2.tar.gz : 03cffeb49d8a1879b621d8f606ac904218019a0ae699b1cd3780a8ee611e696b
homepage   : https://gnome.pages.gitlab.gnome.org/pygobject/
license    : LGPL-2.1-or-later
summary    : Python GObject bindings
description: |
    PyGObject provides Python bindings to the GObject class from GLib.
component  : programming.python
builddeps  :
    - pkgconfig(gobject-introspection-1.0)
    - pkgconfig(py3cairo)
    - pkgconfig(python3)
    - meson-python
    - patchelf
    - python-build
    - python-installer
    - python-setuptools
    - python-wheel
rundeps    :
    - python-cairo
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
replaces   :
    - python3-gobject
    - devel : python3-gobject-devel
conflicts  :
    - devel :
        - python2-gobject-devel
