name       : python-gobject
version    : 3.50.0
release    : 36
source     :
    - https://download.gnome.org/sources/pygobject/3.50/pygobject-3.50.0.tar.xz : 8d836e75b5a881d457ee1622cae4a32bcdba28a0ba562193adb3bbb472472212
homepage   : https://gnome.pages.gitlab.gnome.org/pygobject/
license    : LGPL-2.1-or-later
summary    : Python GObject bindings
description: |
    PyGObject provides Python bindings to the GObject class from GLib.
component  : programming.python
builddeps  :
    - pkgconfig(gobject-introspection-1.0)
    - pkgconfig(py3cairo)
    - pkgconfig(python3)
    - meson-python
    - patchelf
    - python-build
    - python-installer
    - python-packaging
    - python-wheel
rundeps    :
    - python3-cairo
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
replaces   :
    - python3-gobject
    - devel : python3-gobject-devel
conflicts  :
    - devel :
        - python2-gobject-devel
