name       : quadrapassel
version    : '49.0'
release    : 18
source     :
    - https://download.gnome.org/sources/quadrapassel/49/quadrapassel-49.0.tar.xz : 54531edf0f9aa66936aa34079afcc2a5c00025f40168cafb7ebb1db8f242eee1
homepage   : https://gitlab.gnome.org/GNOME/quadrapassel
license    : GPL-2.0-or-later
component  : games.arcade
summary    : Quadrapassel, the GNOME version of Tetris
description: |
    Quadrapassel, the GNOME version of Tetris
builddeps  :
    - pkgconfig(clutter-gtk-1.0)
    - pkgconfig(gee-0.8)
    - pkgconfig(gsound)
    - pkgconfig(libadwaita-1)
    - pkgconfig(libgnome-games-support-1)
    - pkgconfig(librsvg-2.0)
    - pkgconfig(manette-0.2)
    - pkgconfig(yelp-xsl)
    - blueprint-compiler
    - desktop-file-utils
    - itstool
    - vala
    - yelp-tools
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
