name       : gnome-system-monitor
version    : '49.0'
release    : 34
source     :
    - https://download.gnome.org/sources/gnome-system-monitor/49/gnome-system-monitor-49.0.tar.xz : dcc844dd70e4a077f066524dbd14f9cfe04b09831d70b7d69a51816723cd4aa0
homepage   : https://apps.gnome.org/SystemMonitor/
license    : GPL-2.0-or-later
component  : desktop.gnome
summary    : View and manage system resources
description: |
    System Monitor is a process viewer and system monitor with an attractive, easy-to-use interface. System Monitor can help you find out what applications are using the processor or the memory of your computer, can manage the running applications, force stop processes not responding, and change the state or priority of existing processes. The resource graphs feature shows you a quick overview of what is going on with your computer displaying recent network, memory and processor usage.
optimize   :
    - lto
builddeps  :
    - pkgconfig(catch2)
    - pkgconfig(giomm-2.68)
    - pkgconfig(gtkmm-4.0)
    - pkgconfig(libadwaita-1)
    - pkgconfig(libgtop-2.0)
    - pkgconfig(librsvg-2.0)
    - itstool
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
    rm $installdir/usr/share/applications/gnome-system-monitor-kde.desktop
