name       : dconf
version    : 0.49.0
release    : 24
source     :
    - https://download.gnome.org/sources/dconf/0.49/dconf-0.49.0.tar.xz : 16a47e49a58156dbb96578e1708325299e4c19eea9be128d5bd12fd0963d6c36
homepage   : https://gitlab.gnome.org/GNOME/dconf
license    : LGPL-2.1-or-later
component  : desktop.gnome.core
summary    : GNOME Configuration Database
description: |
    The dconf package contains a configuration database system used by many GNOME applications.
emul32     : true
builddeps  :
    - pkgconfig32(dbus-1)
    - pkgconfig32(gio-unix-2.0)
    - docbook-xml
    - vala
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
