name       : python-configargparse
version    : 1.7.1
release    : 14
source     :
    - https://github.com/bw2/ConfigArgParse/archive/refs/tags/1.7.1.tar.gz : b31bfcce183ef7226f00cd07a37cfd69fe654229fe462f9a1de6091f396fc0f9
homepage   : https://github.com/bw2/ConfigArgParse/
license    : MIT
component  : programming.python
summary    : A drop-in replacement for argparse with config file support
description: |
    A drop-in replacement for argparse that allows options to also be set via config files and/or environment variables
builddeps  :
    - python-setuptools
checkdeps  :
    - python-pytest
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest -v
