name       : python-asn1-modules
version    : 0.4.2
release    : 17
source     :
    - https://pypi.io/packages/source/p/pyasn1_modules/pyasn1_modules-0.4.2.tar.gz : 677091de870a80aae844b1ca6134f54652fa2c8c5a52aa396440ac3106e941e6
homepage   : https://github.com/pyasn1/pyasn1-modules
license    : BSD-2-Clause
component  : programming.python
summary    : A collection of ASN.1-based protocols modules
description: |
    A collection of ASN.1 modules expressed in form of pyasn1 classes. Includes protocols PDUs definition (SNMP, LDAP etc.) and various data structures (X.509, PKCS etc.).
builddeps  :
    - python-asn1
    - python-build
    - python-installer
    - python-setuptools
rundeps    :
    - python-asn1
    - python-openssl
build      : |
    %python3_setup
install    : |
    %python3_install
#check      : |
#    %python3_test
