name       : gnome-clocks
version    : '49.0'
release    : 24
source     :
    - https://download.gnome.org/sources/gnome-clocks/49/gnome-clocks-49.0.tar.xz : bf76915f2a492e8a0592fe40b35346593aa39e4e6881d6176e0efd8771d4e6fa
homepage   : https://apps.gnome.org/Clocks/
license    : GPL-2.0-or-later
component  : desktop.gnome
summary    : Keep track of time
description: |
    A simple and elegant clock application. It includes world clocks, alarms, a stopwatch, and timers.
optimize   :
    - lto
builddeps  :
    - pkgconfig(gnome-desktop-4)
    - pkgconfig(gweather4)
    - pkgconfig(libadwaita-1)
    - pkgconfig(libgeoclue-2.0)
    - desktop-file-utils
    - itstool
    - vala
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
