name       : python-django
version    : 5.2.6
release    : 28
source     :
    - https://files.pythonhosted.org/packages/source/d/django/django-5.2.6.tar.gz : da5e00372763193d73cecbf71084a3848458cecf4cee36b9a1e8d318d114a87b
homepage   : https://www.djangoproject.com
license    : BSD-3-Clause
component  : programming.python
summary    : The Web framework for perfectionists with deadlines
description: |
    Django is a high-level Python web framework that encourages rapid development and clean, pragmatic design.
builddeps  :
    - python-build
    - python-installer
    - python-setuptools
    - python-wheel
rundeps    :
    - python-asgiref
    - python-pytz
    - python-sqlparse
build      : |
    %python3_setup
install    : |
    %python3_install
