name       : gvfs
version    : 1.58.0
release    : 103
source     :
    - https://download.gnome.org/sources/gvfs/1.58/gvfs-1.58.0.tar.xz : dd9be36873d0fcb309eb89a8d274770ce576287628a2cf111bd387e1c34f182f
homepage   : https://gitlab.gnome.org/GNOME/gvfs
license    :
    - GPL-2.0-only
component  :
    - desktop.gnome.core
    - goa : desktop.gnome.core
summary    :
    - goa : GNOME Online Accounts support in gvfs
    - Userspace virtual filesystem
description: |
    The Gvfs package is a userspace virtual filesystem designed to work with the I/O abstractions of GLib's GIO library.
patterns   :
    - goa :
        - /usr/lib64/gvfs/gvfsd-google
        - /usr/lib/systemd/user/gvfs-goa-volume-monitor.service
        - /usr/lib64/gvfs/gvfs-goa-volume-monitor
        - /usr/share/dbus-1/services/org.gtk.vfs.GoaVolumeMonitor.service
        - /usr/share/gvfs/remote-volume-monitors/goa.monitor
        - /usr/share/gvfs/mounts/google.mount
builddeps  :
    - pkgconfig(avahi-glib)
    - pkgconfig(fuse3)
    - pkgconfig(gcr-4)
    - pkgconfig(gnome-keyring-1)
    - pkgconfig(goa-1.0)
    - pkgconfig(gsettings-desktop-schemas)
    - pkgconfig(gudev-1.0)
    - pkgconfig(libarchive)
    - pkgconfig(libbluray)
    - pkgconfig(libcap)
    - pkgconfig(libcdio_paranoia)
    - pkgconfig(libgcrypt)
    - pkgconfig(libgdata)
    - pkgconfig(libgphoto2)
    - pkgconfig(libimobiledevice-1.0)
    - pkgconfig(libmtp)
    - pkgconfig(libnfs)
    - pkgconfig(libsecret-unstable)
    - pkgconfig(libsoup-3.0)
    - pkgconfig(msgraph-1)
    - pkgconfig(smbclient)
    - pkgconfig(udisks2)
    - cifs-utils-devel
    - openssh
rundeps    :
    - goa : gvfs
    - lsof
setup      : |
    %patch -p1 -i $pkgfiles/0002-monitor-Do-not-load-monitors-when-GIO_USE_VFS-local.patch
    %meson_configure -Dprivileged_group=sudo
build      : |
    %ninja_build
install    : |
    %ninja_install
