name       : xdg-desktop-portal-gnome
version    : '49.0'
release    : 15
source     :
    - https://download.gnome.org/sources/xdg-desktop-portal-gnome/49/xdg-desktop-portal-gnome-49.0.tar.xz : 401dafcdf8cb911f09c08d2813f774dd864127abfca93ff4caf1fc4c9b5ec4d2
homepage   : https://gitlab.gnome.org/GNOME/xdg-desktop-portal-gnome
license    : LGPL-2.1-or-later
component  : desktop.util
summary    : A backend implementation for xdg-desktop-portal for the GNOME desktop environment.
description: |
    A backend implementation for xdg-desktop-portal for the GNOME desktop environment.
builddeps  :
    - pkgconfig(gnome-desktop-4)
    - pkgconfig(libadwaita-1)
    - pkgconfig(xdg-desktop-portal)
    - gnome-keyring
rundeps    :
    - nautilus
    - xdg-desktop-portal-gtk
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
