name       : python-icecream
version    : 2.1.8
release    : 5
source     :
    - https://files.pythonhosted.org/packages/source/i/icecream/icecream-2.1.8.tar.gz : 37269bbc62b02f0d85bfaf3a0eb4df272c967fad059f7ddcdaee5303ea2b2a62
homepage   : https://github.com/gruns/icecream
license    : MIT
component  : programming.python
summary    : Never use print() to debug again
description: |
    Do you ever use print() or log() to debug your code? Of course you do. IceCream, or ic for short, makes print debugging a little sweeter.
builddeps  :
    - python-build
    - python-installer
    - python-setuptools
rundeps    :
    - pygments
    - python-asttokens
    - python-colorama
    - python-executing
build      : |
    %python3_setup
install    : |
    %python3_install
