name       : strace
version    : '6.12'
release    : 13
source     :
    - https://github.com/strace/strace/releases/download/v6.12/strace-6.12.tar.xz : c47da93be45b6055f4dc741d7f20efaf50ca10160a5b100c109b294fd9c0bdfe
license    : BSD-3-Clause
summary    : Diagnostic, debugging and instructional userspace utility
component  : programming.tools
description: |
    Strace is a diagnostic, debugging and instructional userspace utility for Linux. It is used to monitor and tamper with interactions between processes and the Linux kernel, which include system calls, signal deliveries, and changes of process state.
homepage   : https://strace.io/
builddeps  :
    - pkgconfig(libunwind)
clang      : yes
setup      : |
    %configure --with-libunwind
build      : |
    %make
install    : |
    %make_install
