name       : decibels
version    : '49.0'
release    : 4
source     :
    - https://download.gnome.org/sources/decibels/49/decibels-49.0.tar.xz : 29b79ba2e2967e69141e39f0ad2c677e38fe3ffb9fba0fa5c7531f94d3f673ca
homepage   : https://apps.gnome.org/Decibels/
license    : GPL-3.0-or-later
component  : multimedia.audio
summary    : Play audio files
description: |
    Decibels play audio files, shows the waveform of the track, adjust playback speed and easy seek controls.
builddeps  :
    - pkgconfig(gjs-1.0)
    - pkgconfig(libadwaita-1)
    - blueprint-compiler
    - desktop-file-utils
    - nodejs
    - typescript
rundeps    :
    - gjs
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
