name       : safeeyes
version    : 3.2.0
release    : 17
source     :
    - https://github.com/slgobinath/SafeEyes/archive/refs/tags/v3.2.0.tar.gz : 57caf4932c36a531d5c97f94e8d8556f16e4032c9efbe313e20217657dc7d8f9
homepage   : http://slgobinath.github.io/SafeEyes/
license    : GPL-3.0-or-later
component  : desktop
summary    : Safe Eyes is a tool to reduce and prevent repetitive strain injury (RSI)
description: |
    Protect your eyes from eye strain using this simple and beautiful, yet extensible break reminder.
builddeps  :
    - python-build
    - python-installer
    - python-setuptools
rundeps    :
    - libnotify
    - pipewire
    - python-babel
    - python-croniter
    - python-gobject
    - python-packaging
    - python-xlib
    - python-pywayland
    - xprintidle
build      : |
    %python3_setup
install    : |
    %python3_install

    # Remove duplicate icons and desktop file.
    rm -rv $installdir/usr/lib/python%python3_version%/site-packages/safeeyes/platform
