name       : yelp
version    : '49.0'
release    : 34
source     :
    - https://download.gnome.org/sources/yelp/49/yelp-49.0.tar.xz : e6614e0b1f4ba5fe7b8d149bdd42673f030656fbdcd736ae9860719197c63457
homepage   : http://yelp.io/
license    : GPL-2.0-or-later
component  : desktop.gnome
summary    : GNOME Help Browser
description: |
    Yelp is the default help browser for the GNOME desktop.  Yelp provides a simple graphical interface for viewing DocBook, HTML, man, and info formatted documentation.  The name Yelp was suggested by Daniel Lundin. Yelp is pronounced the same as the swedish word for help.
builddeps  :
    - pkgconfig(bzip2)
    - pkgconfig(libadwaita-1)
    - pkgconfig(libgcrypt)
    - pkgconfig(libhandy-1)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(libxslt)
    - pkgconfig(sqlite3)
    - pkgconfig(webkitgtk-6.0)
    - pkgconfig(yelp-xsl)
    - desktop-file-utils
    - itstool
rundeps    :
    - docbook-xml
    - yelp-xsl
setup      : |
    %meson_configure \
             -Dlzma=enabled \
             -Dbzip2=enabled
build      : |
    %ninja_build
install    : |
    %ninja_install
