name       : gnome-builder
version    : '49.0'
release    : 110
source     :
    - https://download.gnome.org/sources/gnome-builder/49/gnome-builder-49.0.tar.xz : d45990db681f95ee2277be4fa9f2964982707dbdf30130a0bde70234b379f562
homepage   : https://apps.gnome.org/Builder/
license    : GPL-3.0-or-later
component  : programming.ide
summary    : An IDE for GNOME
description: |
    Builder is an actively developed Integrated Development Environment for GNOME. It combines integrated support for essential GNOME technologies such as GTK+, GLib, and GNOME APIs with features that any developer will appreciate, like syntax highlighting and snippets.
builddeps  :
    - pkgconfig(editorconfig)
    - pkgconfig(enchant-2)
    - pkgconfig(flatpak)
    - pkgconfig(gjs-1.0)
    - pkgconfig(gom-1.0)
    - pkgconfig(gtksourceview-5)
    - pkgconfig(jsonrpc-glib-1.0)
    - pkgconfig(libadwaita-1)
    - pkgconfig(libcmark)
    - pkgconfig(libdex-1)
    - pkgconfig(libgit2-glib-1.0)
    - pkgconfig(libpanel-1)
    - pkgconfig(libpeas-2)
    - pkgconfig(libportal-gtk4)
    - pkgconfig(libspelling-1)
    - pkgconfig(mm-common-util)
    - pkgconfig(sysprof-capture-4)
    - pkgconfig(template-glib-1.0)
    - pkgconfig(vte-2.91)
    - pkgconfig(webkitgtk-6.0)
    - pkgconfig(yaml-0.1)
    - clang-devel
    - ctags
    - desktop-file-utils
    - itstool
    - vala
rundeps    :
    - ctags
    - flatpak
    - python-jedi
    - python-lxml
    - valgrind # Ensure the "run with valgrind" support works OOTB
clang      : true
setup      : |
    export CFLAGS="$CFLAGS -Wno-error -Wno-incompatible-pointer-types-discards-qualifiers -Wno-shadow -Wno-array-bounds"

    %meson_configure \
        -Dplugin_autotools=true \
        -Dplugin_cargo=true \
        -Dplugin_ctags=true \
        -Dplugin_flatpak=true \
        -Dplugin_make=true \
        -Dplugin_meson=true \
        -Dplugin_spellcheck=true \
        -Dplugin_sysprof=true \
        -Dplugin_update_manager=false
build      : |
    %ninja_build
install    : |
    %ninja_install
