name       : pysolfc
version    : 3.4.1
release    : 20
source     :
    - https://sourceforge.net/projects/pysolfc/files/PySolFC/PySolFC-3.4.1/PySolFC-3.4.1.tar.xz : 3b9bfb91f8f75b7cb9cc836424606975c5a0868c7b50c6917e51367a7c82e6cb
homepage   : https://pysolfc.sourceforge.io/
license    : GPL-3.0-or-later
component  : games.card
summary    : PySol Fan Club edition
description: |
    PySol Fan Club Edition (PySolFC) is a collection of more than 1000 solitaire card games.
builddeps  :
    - python-build
    - python-installer
    - python-setuptools
rundeps    :
    - pysolfc-cardsets
    - python-attrs
    - python-configobj
    - python-pillow
    - python-pysol-cards
    - python3-tkinter
build      : |
    %python3_setup
install    : |
    %python3_install
    install -Dm00644 $pkgfiles/io.sourceforge.pysolfc.PySolFC.metainfo.xml -t $installdir/usr/share/metainfo/
