name       : gnome-logs
version    : '49.0'
release    : 24
source     :
    - https://download.gnome.org/sources/gnome-logs/49/gnome-logs-49.0.tar.xz : f8f579eb0bb6d9a8d6ae5ee1423f9447af91200785178b50bbadd4ac2d255d45
homepage   : https://apps.gnome.org/Logs/
license    : GPL-3.0-or-later
component  : system.utils
summary    : View detailed event logs for the system
description: |
    Logs shows events from the systemd journal, and sorts them into categories, such as hardware and applications. Using Logs you can search your logs by typing a search term, and view detailed information about each event by clicking on it.
builddeps  :
    - pkgconfig(gtk4)
    - pkgconfig(libadwaita-1)
    - desktop-file-utils
    - docbook-xml
    - itstool
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
