name       : yosys
version    : '0.36'
release    : 22
source     :
    - https://github.com/YosysHQ/yosys/archive/yosys-0.36.tar.gz : d69beedcb76db80681c2a0f445046311f3ba16716d5d0c3c5034dabcb6bd9b23
    - https://github.com/YosysHQ/yosys/releases/download/yosys-0.36/abc.tar.gz : a453ead5c6ee63a87588be63669bfc919cfe9a9b9b3a76d438fc11d90a6a9666
homepage   : https://yosyshq.net/yosys/
license    : ISC
component  : office.scientific
summary    : Yosys Open SYnthesis Suite
description: |
    Yosys is a framework for Verilog RTL synthesis. It currently has extensive Verilog-2005 support and provides a basic set of synthesis algorithms for various application domains.
patterns   :
    - devel :
        - /usr/bin/yosys-config
        - '%libdir%/libyosys.so'
        - /usr/share/yosys/include
builddeps  :
    - pkgconfig(libffi)
    - pkgconfig(libxcrypt)
    - pkgconfig(python3)
    - pkgconfig(tcl)
    - git
    - iverilog
    - libboost-devel
setup      : |
    tar xf $sources/abc.tar.gz
    mv YosysHQ-abc-896e5e7 abc
    make ABCREV=default PREFIX=/usr config-gcc
    sitedir=$(python3 -c "import site; print(site.getsitepackages()[0])")
    echo "PREFIX=/usr"          >> Makefile.conf
    echo "LIBDIR=%libdir%"      >> Makefile.conf
    echo "ENABLE_LIBYOSYS=1"    >> Makefile.conf
    echo "ENABLE_PYOSYS=1"      >> Makefile.conf
    echo "PYTHON_DESTDIR=${sitedir}" >> Makefile.conf
build      : |
    %make ABCREV=default BOOST_PYTHON_LIB="-lpython%python3_version% -lboost_python311"
check      : |
    (cd tests/simple  && bash run-test.sh)
    (cd tests/fsm     && bash run-test.sh)
    (cd tests/svtypes && bash run-test.sh)
    (cd tests/verilog && bash run-test.sh)
install    : |
    %make_install ABCREV=default
    # remove redundant copy of .so file
    rm -f $installdir/usr/bin/*.so

