name       : tecla
version    : '49.0'
release    : 5
source     :
    - https://download.gnome.org/sources/tecla/49/tecla-49.0.tar.xz : 2ca424e402baf60cd6b13777703b701ebb1faf8f3d0f2f971144d823f651249f
homepage   : https://gitlab.gnome.org/GNOME/tecla
license    : GPL-2.0-or-later
component  : desktop.library
summary    : Keyboard layout viewer
description: |
    Tecla is a keyboard layout viewer
builddeps  :
    - pkgconfig(libadwaita-1)
    - pkgconfig(wayland-egl)
    - pkgconfig(xkbregistry)
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
