name       : gnome-font-viewer
version    : '49.0'
release    : 26
source     :
    - https://download.gnome.org/sources/gnome-font-viewer/49/gnome-font-viewer-49.0.tar.xz : 7c018925c285771b55d7d1a6f15711c0c193d7450ed9871e20d44f2548562404
homepage   : https://apps.gnome.org/FontViewer/
license    : GPL-2.0-or-later
component  : desktop.gnome
summary    : View fonts on your system
description: |
    Fonts shows you the fonts installed on your computer for your use as thumbnails. Selecting any thumbnails shows the full view of how the font would look under various sizes. Fonts also supports installing new font files downloaded in the .ttf and other formats. Fonts may be installed only for your use or made available to all users on the computer.
optimize   :
    - lto
builddeps  :
    - pkgconfig(gnome-desktop-3.0)
    - pkgconfig(harfbuzz)
    - pkgconfig(libadwaita-1)
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
