name       : gnome-contacts
version    : '49.0'
release    : 24
source     :
    - https://download.gnome.org/sources/gnome-contacts/49/gnome-contacts-49.0.tar.xz : 25f21c67bc29d77def2d9cd3e22d28460d12b47ff248a2017731b54db485e4af
homepage   : https://apps.gnome.org/Contacts/
license    : GPL-2.0-or-later
component  : office
summary    : Manage your contacts
description: |
    Contacts keeps and organize your contacts information. You can create, edit, delete and link together pieces of information about your contacts. Contacts aggregates the details from all your sources providing a centralized place for managing your contacts. Contacts will also integrate with online address books and automatically link contacts from different online sources.
builddeps  :
    - pkgconfig(accountsservice)
    - pkgconfig(champlain-0.12)
    - pkgconfig(cheese-gtk)
    - pkgconfig(clutter-gtk-1.0)
    - pkgconfig(folks)
    - pkgconfig(gee-0.8)
    - pkgconfig(gnome-desktop-3.0)
    - pkgconfig(goa-1.0)
    - pkgconfig(gobject-introspection-1.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libadwaita-1)
    - pkgconfig(libcanberra)
    - pkgconfig(libebook-1.2)
    - pkgconfig(libportal-gtk4)
    - pkgconfig(libqrencode)
    - pkgconfig(libsecret-1)
    - pkgconfig(telepathy-glib)
    - blueprint-compiler
    - desktop-file-utils
    - docbook-xml
    - vala
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
