name       : python-pytest-httpserver
version    : 1.1.3
release    : 13
source     :
    - https://github.com/csernazs/pytest-httpserver/archive/refs/tags/1.1.3.tar.gz : 5ca7247206fc6d5620986cdc4fd0706046ff468165907e73d60c64fd3313674c
homepage   : https://github.com/csernazs/pytest-httpserver
license    : MIT
component  : programming.python
summary    : pytest-httpserver is a httpserver for pytest
description: |
    This library is designed to help to test http clients without contacting the real http server. In other words, it is a fake http server which is accessible via localhost can be started with the pre-defined expected http requests and their responses.
builddeps  :
    - python-build
    - python-installer
    - python-poetry
    - python-pytest   # check
    - python-toml     # check
    - python-werkzeug # check
rundeps    :
    - python-werkzeug
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest -v
