name       : python-contourpy
version    : 1.3.3
release    : 8
source     :
    - https://files.pythonhosted.org/packages/source/c/contourpy/contourpy-1.3.3.tar.gz : 083e12155b210502d0bca491432bb04d56dc3432f95a979b429f2848c3dbe880
homepage   : https://github.com/contourpy/contourpy
license    : BSD-3-Clause
component  : programming.python
summary    : Python library for calculating contours in 2D quadrilateral grids
description: |
    ContourPy is a Python library for calculating contours of 2D quadrilateral grids. It is written in C++11 and wrapped using pybind11.
builddeps  :
    - pkgconfig(python3)
    - meson-python
    - patchelf
    - pybind11
    - python-build
    - python-installer
rundeps    :
    - numpy
setup      : |
    sed -e '/ninja/d' -i pyproject.toml
build      : |
    %python3_setup
install    : |
    %python3_install
