name       : gnome-software
version    : '49.0'
release    : 31
source     :
    - https://download.gnome.org/sources/gnome-software/49/gnome-software-49.0.tar.xz : 369cd7543f0a4be9a33733de0af156348266c3b5cacaa4e4737959e7d14e041f
homepage   : https://apps.gnome.org/Software/
license    : GPL-2.0-or-later
component  : desktop.gnome
summary    : GNOME Software allows users to easily find, discover and install apps.
description: |
    GNOME Software allows users to easily find, discover and install apps. It also keeps their OS, apps and devices up to date without them having to think about it, and gives them confidence that their system is up to date. It supports popular distributions, subject to those distributions maintaining their own distro-specific integration code.
optimize   :
    - lto
builddeps  :
    - pkgconfig(appstream)
    - pkgconfig(flatpak)
    - pkgconfig(fwupd)
    - pkgconfig(gsettings-desktop-schemas)
    - pkgconfig(gtk4)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libadwaita-1)
    - pkgconfig(libsoup-3.0)
    - pkgconfig(packagekit-glib2)
    - pkgconfig(xmlb)
    - gtk-doc
    - itstool
rundeps    :
    - gnome-app-list
setup      : |
    # reenable me!
    #patch -p1 -i $pkgfiles/0001-gs-appstream-Check-against-kernel-relation-types.patch
    %patch -p1 -i $pkgfiles/0001-packagekit-Hardcode-some-solus-thingies.patch
    %patch -p1 -i $pkgfiles/0001-packagekit-Set-PK_INFO_ENUM_SECURITY-as-AS_URGENCY_K.patch
    # https://gitlab.gnome.org/GNOME/gnome-software/-/issues/2610
    %patch -p1 -i $pkgfiles/0001-packagekit-HACK-Disable-req.-for-repo-plugin-to-show.patch
    %patch -p1 -i $pkgfiles/0001-Show-console-apps.patch

    %meson_configure \
        -Dpackagekit_autoremove=true \
        -Dmalcontent=false \
        -Dtests=false
build      : |
    %ninja_build
install    : |
    %ninja_install

    install -Dm00644 $pkgfiles/org.gnome.software.gschema.override $installdir/usr/share/glib-2.0/schemas/org.gnome.software.gschema.override
