name       : gnome-shell-extension-dash-to-dock
version    : '102'
release    : 29
source     :
    - https://github.com/micheleg/dash-to-dock/archive/refs/tags/extensions.gnome.org-v102.tar.gz : 187caa454fa4820193a6adfb7855f6772d1f9b624f5f651b26c0fe5774d72b3a
homepage   : https://github.com/micheleg/dash-to-dock
license    : GPL-2.0-only
component  : desktop.gnome
summary    : A dock for the Gnome Shell.
description: |
    A dock for the Gnome Shell. This extension moves the dash out of the overview transforming it in a dock for an easier launching of applications and a faster switching between windows and desktops.
rundeps    :
    - gnome-shell
    - gnome-shell-extensions
builddeps  :
    - sassc
build      : |
    %make
install    : |
    #install -dm00755 $installdir/usr/share/glib-2.0/schemas/
    #install -Dm00644 schemas/org.gnome.shell.extensions.dash-to-dock.gschema.xml $installdir/usr/share/glib-2.0/schemas/org.gnome.shell.extensions.dash-to-dock.gschema.xml
    %make_install VERSION=$version
