name       : ypkg
version    : '34'
release    : 201
source     :
    - git|https://github.com/getsolus/ypkg.git : 1eb78bff7cdbf1e3835dbe07b0efe0ac12e4a1a9
homepage   : https://github.com/getsolus/ypkg
license    : GPL-3.0-or-later
component  : system.devel
summary    : Modern, declarative, structured build format
description: |
    ypkg is the build tool of choice for Solus.

    Simply put, it is a tool to convert a build process into a packaging operation.
mancompress: yes
strip      : no
debug      : no
builddeps  :
    - pkgconfig(python3)
    - nuitka
    - patchelf
    - python-eopkg
    - python-xattr
    - python-zstandard
    - tree
rundeps    :
    - python-eopkg
    - python-xattr
    - pyyaml
    - ruamel_yaml
clang      : yes
environment: |
    # ensure our nuitka build doesn't pull in -v3 hwcaps libs
    export GLIBC_TUNABLES=glibc.cpu.hwcaps=-AVX
setup      : |
    %patch -p1 -i $pkgfiles/0001-examine-Fix-runpath-detection.patch

    %python3_setup
build      : |
    # build static bins from ypkg
    # --include-package-data=ypkg is necessary to get rc.yml included (will include all non-py files actually)
    time nuitka3 --onefile --include-module=dbm.gnu --show-scons --lto=yes --no-deployment-flag=self-execution --main=ypkg --main=ypkg-build --main=ypkg-install-deps --main=ypkg-gen-history --include-package-data=ypkg2 --jobs=%YJOBS%
install    : |
    %python3_install

    # Install main ypkg binary
    mv $installdir/usr/bin/ypkg $installdir/usr/bin/ypkg.py
    install -Dm0755 $workdir/ypkg.bin -t $installdir/usr/bin/
    ln -srvf $installdir/usr/bin/ypkg.bin $installdir/usr/bin/ypkg

    # Create symlinks for the other binaries
    for b in ypkg-build ypkg-install-deps ypkg-gen-history
    do
        mv $installdir/usr/bin/$b $installdir/usr/bin/$b.py
        # this can be used to switch the used version between the nuitka .bin ones and the pure .py ones
        #ln -srvf $installdir/usr/bin/$b.py $installdir/usr/bin/$b
        ln -srvf $installdir/usr/bin/ypkg $installdir/usr/bin/$b
    done
    # show the current symlink targets for convenience
    tree -P 'y*' $installdir/usr/bin/
