name       : gjs
version    : 1.82.1
release    : 63
source     :
    - https://download.gnome.org/sources/gjs/1.82/gjs-1.82.1.tar.xz : fb39aa5636576de0e5a1171f56a1a5825e2bd1a69972fb120ba78bd109b5693c
component  : desktop.gnome.core
homepage   : https://gjs.guide/
license    :
    - MIT OR LGPL-2.0-or-later
summary    : GNOME JavaScript
description: |
    GJS is a JavaScript runtime built on Firefox's SpiderMonkey JavaScript engine and the GNOME platform libraries.
optimize   :
    - lto
builddeps  :
    - pkgconfig(cairo)
    - pkgconfig(gtk4)
    - pkgconfig(mozjs-128)
rundeps    :
    - mozjs
setup      : |
    %meson_configure -Dinstalled_tests=false
build      : |
    %ninja_build
install    : |
    %ninja_install
