name       : gjs
version    : 1.86.0
release    : 66
source     :
    - https://download.gnome.org/sources/gjs/1.86/gjs-1.86.0.tar.xz : 63448f7a57804d4c2a8d0c7f5e90e224d04d4eb2d560142c076c65a8eda00799
component  : desktop.gnome.core
homepage   : https://gjs.guide/
license    :
    - MIT OR LGPL-2.0-or-later
summary    : GNOME JavaScript
description: |
    GJS is a JavaScript runtime built on Firefox's SpiderMonkey JavaScript engine and the GNOME platform libraries.
optimize   :
    - lto
builddeps  :
    - pkgconfig(cairo)
    - pkgconfig(gtk4)
    - pkgconfig(mozjs-140)
rundeps    :
    - mozjs
setup      : |
    %meson_configure -Dinstalled_tests=false
build      : |
    %ninja_build
install    : |
    %ninja_install
