name       : rapidyaml
version    : 0.8.0
release    : 1
source     :
    - https://github.com/biojppm/rapidyaml/archive/refs/tags/v0.8.0.tar.gz : 6df750751fa608d6e6226bb3b91b0415236ee2377a02952b86c022ebb08e98c9
homepage   : https://github.com/biojppm/rapidyaml
license    : MIT
component  :
    - programming.library
    - # qt5 : programming.library
    - # qt6 : programming.library
summary    : Rapid YAML is a C++ library for parsing and generating YAML
description: |
    Rapid YAML or ryml, for short. ryml is a C++ library to parse and emit YAML, and do it fast, on everything from x64 to bare-metal chips without operating system.
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
profile    : |
    %ninja_check
install    : |
    %ninja_install
    mv $installdir/usr/lib $installdir/%libdir%
