name       : python-dulwich
version    : 0.24.1
release    : 7
source     :
    - https://files.pythonhosted.org/packages/source/d/dulwich/dulwich-0.24.1.tar.gz : e19fd864f10f02bb834bb86167d92dcca1c228451b04458761fc13dabd447758
homepage   : https://github.com/jelmer/dulwich
license    : Apache-2.0
component  : programming.python
summary    : Pure-Python Git implementation
description: |
    This is the Dulwich project. It aims to provide an interface to git repos (both local and remote) that doesn't call out to git directly but instead uses pure Python.
networking : true
builddeps  :
    - python-build
    - python-installer
    - python-setuptools
    - python-setuptools-rust
build      : |
    %python3_setup
install    : |
    %python3_install
