name       : python3
version    : 3.11.11
release    : 69
source     :
    - https://www.python.org/ftp/python/3.11.11/Python-3.11.11.tar.xz : 2a9920c7a0cd236de33644ed980a13cbbc21058bfdc528febb6081575ed73be3
    # If the bundled versions should be used don't delete these, just comment them out. The build script checks for them dynamically.
    - https://pypi.debian.net/pip/pip-24.3.1-py3-none-any.whl : 3790624780082365f47549d032f3770eeb2b1e8bd1f7b2e02dace1afa361b4ed
    - https://pypi.debian.net/setuptools/setuptools-75.6.0-py3-none-any.whl : ce74b49e8f7110f9bf04883b730f4765b774ef3ef28f722cce7c273d253aaf7d
homepage   : https://www.python.org/
license    : Python-2.0
summary    :
    - Python development environment - 3.11
    - test : Python 3.11 Test package
component  :
    - programming.python
    - test : programming.python
    - tkinter : programming.python
description: |
    The Python 3 package contains the Python development environment. This is useful for object-oriented programming, writing scripts, prototyping large programs or developing entire applications.
optimize   :
    - speed
    - no-frame-pointer # Temporary, remove when Python 3.12 is out (https://docs.python.org/3.12/howto/perf_profiling.html)
networking : yes
builddeps  :
    - pkgconfig(bzip2)
    - pkgconfig(harfbuzz) # Fix linking for tkinter
    - pkgconfig(libffi)
    - pkgconfig(liblzma)
    - pkgconfig(libxcrypt)
    - pkgconfig(openssl)
    - pkgconfig(sqlite3)
    - pkgconfig(tcl)
    - pkgconfig(tk)
    - pkgconfig(x11)
    - db5-devel
    - gdbm-devel
replaces   :
    - python3-setuptools
rundeps    :
    - test : python3
    - tkinter : python3
patterns   :
    - /usr/include/python3.*/pyconfig.h
    - devel :
        - /usr/lib/python3.*/config-3.*-x86_64-linux-gnu/libpython3.*.a
    - test :
        - /usr/lib/python3.*/test
    - tkinter :
        - /usr/lib64/python3.*/lib-dynload/_tkinter.cpython-3*-x86_64-linux-gnu.so*
setup      : |
    %apply_patches

    # Upgrade pip and setuptools if updated .whl files for them exist in the sources
    if compgen -G "$sources/pip*.whl" > /dev/null; then
        pip_version=$(ls -1 $sources | grep pip | head -1 | cut -d "-" -f 2)
        sed -i "s|^_PIP_VERSION.*|_PIP_VERSION = \"$pip_version\"|" Lib/ensurepip/__init__.py
        rm -v Lib/ensurepip/_bundled/pip-*-py3-none-any.whl
        cp $sources/pip-*-py3-none-any.whl Lib/ensurepip/_bundled/
    fi
    if compgen -G "$sources/setuptools*.whl" > /dev/null; then
        setuptools_version=$(ls -1 $sources | grep setuptools | head -1 | cut -d "-" -f 2)
        sed -i "s|^_SETUPTOOLS_VERSION.*|_SETUPTOOLS_VERSION = \"$setuptools_version\"|" Lib/ensurepip/__init__.py
        rm -v Lib/ensurepip/_bundled/setuptools-*-py3-none-any.whl
        cp $sources/setuptools-*-py3-none-any.whl Lib/ensurepip/_bundled/
    fi

    %configure --enable-ipv6=yes \
               --enable-loadable-sqlite-extensions \
               --enable-optimizations \
               --enable-shared \
               --with-ensurepip=install \
               --with-lto \
               --with-system-expat \
               --with-system-ffi \
               --without-cxx-main \
               ax_cv_c_float_words_bigendian=no \
               CFLAGS="$CFLAGS -I/usr/include"
build      : |
    %make
install    : |
    %make_install

    # We can't use the python3_version macro since we're building Python3 here
    python3_version=$($installdir/usr/bin/python3 -c 'import sys; print(".".join(map(str, sys.version_info[:2])))')
    site_packages_dir=$($installdir/usr/bin/python3 -c "import site; print(site.getsitepackages()[0])")

    install -Dm00644 Tools/gdb/libpython.py $installdir/usr/share/gdb/auto-load/usr/lib64/libpython${python3_version}.so.1.0-gdb.py
    rm $installdir/usr/bin/2to3

    # Generate shell completions for pip
    PYTHONPATH="$installdir/$site_packages_dir" "$installdir"/usr/bin/pip3 completion --bash | install -vDm 644 /dev/stdin "$installdir"/usr/share/bash-completion/completions/pip
    PYTHONPATH="$installdir/$site_packages_dir" "$installdir"/usr/bin/pip3 completion --zsh | tail -n+3 | install -vDm 644 /dev/stdin "$installdir"/usr/share/zsh/site-functions/_pip
    PYTHONPATH="$installdir/$site_packages_dir" "$installdir"/usr/bin/pip3 completion --fish | install -vDm 644 /dev/stdin "$installdir"/usr/share/fish/vendor_completions.d/pip.fish

    # Unneeded on Linux
    find "$installdir" -name '*.exe' -print -delete
