name       : gnome-boxes
version    : '49.0'
release    : 65
source     :
    - https://download.gnome.org/sources/gnome-boxes/49/gnome-boxes-49.0.tar.xz : fa47266da6f5ef7a904c5b8769d4d871bccd4e6b639a363c3235438d7b0e757a
license    : GPL-2.0-only
homepage   : https://apps.gnome.org/Boxes/
component  : virt
summary    : Virtualization made simple
description: |
    Select an operating system and let Boxes download and install it for you in a virtual machine.
    Features:
        - Download freely available operating systems
        - Automatically install CentOS Stream, Debian, Fedora, Microsoft Windows, OpenSUSE, Red Hat Enterprise Linux, and Ubuntu
        - Create virtual machines from operating system images with a couple of clicks
        - Limit the resources (memory and storage) your virtual machines consume from your system
        - Take snapshots of virtual machines to restore to previous states
        - Redirect USB devices from your physical machine into virtual machines
        - 3D acceleration for some of the supported operating systems
        - Automatically resize virtual machines displays to the window size
        - Share clipboard between your system and virtual machines
        - Share files to virtual machines by dropping them from your file manager into the Boxes window
        - Setup Shared Folders between your system and virtual machines
optimize   :
    - lto
builddeps  :
    - pkgconfig(gtk-vnc-2.0)
    - pkgconfig(gtksourceview-4)
    - pkgconfig(libarchive)
    - pkgconfig(libhandy-1)
    - pkgconfig(libosinfo-1.0)
    - pkgconfig(libportal-gtk3)
    - pkgconfig(libsecret-1)
    - pkgconfig(libusb-1.0)
    - pkgconfig(libvirt-glib-1.0)
    - pkgconfig(spice-client-gtk-3.0)
    - pkgconfig(spice-protocol)
    - pkgconfig(tinysparql-3.0)
    - pkgconfig(vte-2.91)
    - pkgconfig(webkit2gtk-4.1)
    - pkgconfig(winpr2)
    - desktop-file-utils
    - git
    - intltool
    - itstool
    - vala
patterns   :
    - /usr/share/man
rundeps    :
    - qemu
    - spice
    - virglrenderer
setup      : |
    %meson_configure -Ddistributor_name=Solus
build      : |
    %ninja_build
install    : |
    %ninja_install
