name       : gnome-maps
version    : '49.0'
release    : 68
source     :
    - https://download.gnome.org/sources/gnome-maps/49/gnome-maps-49.0.tar.xz : 462967b3b01dd608586f662396a78f833b8445f00db56c8199569c8758c361d0
homepage   : https://apps.gnome.org/Maps/
license    : GPL-2.0-or-later
component  : office
summary    : Find places around the world
description: |
    Maps gives you quick access to maps all across the world. It allows you to quickly find the place you’re looking for by searching for a city or street, or locate a place to meet a friend. Maps uses the collaborative OpenStreetMap database, made by hundreds of thousands of people across the globe.
builddeps  :
    - pkgconfig(geoclue-2.0)
    - pkgconfig(gjs-1.0)
    - pkgconfig(gweather4)
    - pkgconfig(libadwaita-1)
    - pkgconfig(libportal)
    - pkgconfig(librsvg-2.0)
    - pkgconfig(rest-1.0)
    - pkgconfig(shumate-1.0)
    - desktop-file-utils
rundeps    :
    - geoclue
    - gjs
    - libgeocode-glib2
    - libgweather
    - librest
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
