name       : python-executing
version    : 2.2.1
release    : 6
source     :
    - https://files.pythonhosted.org/packages/source/e/executing/executing-2.2.1.tar.gz : 3632cc370565f6648cc328b32435bd120a1e4ebb20c77e3fdde9a13cd1e533c4
homepage   : https://github.com/alexmojaki/executing
license    : MIT
component  : programming.python
summary    : Get the currently executing AST node of a frame, and other information
description: |
    This mini-package lets you get information about what a frame is currently doing, particularly the AST node being executed.
builddeps  :
    - python-build
    - python-installer
    - python-setuptools-scm
    - python-wheel
build      : |
    %python3_setup
install    : |
    %python3_install
