name       : python-evdev
version    : 1.9.2
release    : 19
source     :
    - https://github.com/gvalkov/python-evdev/archive/refs/tags/v1.9.2.tar.gz : 1cfb65765b8c63e587110d9b42fa26806bd6dd76565c55c3618afd4c4c48c5a5
homepage   : https://github.com/gvalkov/python-evdev
license    : BSD-3-Clause
component  : programming.python
summary    : Python bindings for the Linux input subsystem
description: |
    This package provides bindings to the generic input event interface in Linux. The evdev interface serves the purpose of passing events generated in the kernel directly to userspace through character devices that are typically located in /dev/input/. This package also comes with bindings to uinput, the userspace input subsystem. Uinput allows userspace programs to create and handle input devices that can inject events directly into the input subsystem.
builddeps  :
    - pkgconfig(python3)
    - python-build
    - python-installer
    - python-setuptools
checkdeps  :
    - python-pytest
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test py.test3 -v -k "not test_uinput"
