name       : python-rtree
version    : 1.4.1
release    : 12
source     :
    - https://github.com/Toblerity/rtree/archive/refs/tags/1.4.1.tar.gz : fd72fdcf63af6c5cf613d4bc9b7cb7de07fa9a654d692d7936b82ba6291cc7ce
homepage   : https://github.com/Toblerity/rtree
license    : MIT
component  : programming.python
summary    : R-Tree spatial index for Python GIS
description: |
    Rtree is a ctypes Python wrapper of libspatialindex that provides a number of advanced spatial indexing features for the spatially curious Python user.
builddeps  :
    - python-build
    - python-installer
    - python-setuptools
    - python-wheel
checkdeps  :
    - libspatialindex
    - numpy
    - python-pytest
rundeps    :
    - libspatialindex
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest -v
