name       : python-asyncssh
version    : 2.21.0
release    : 6
source     :
    - https://files.pythonhosted.org/packages/source/a/asyncssh/asyncssh-2.21.0.tar.gz : 450fe13bb8d86a8f4e7d7b5fafce7791181ca3e7c92e15bbc45dfb25866e48b3
homepage   : https://github.com/ronf/asyncssh
license    : EPL-2.0
component  : programming.python
summary    : Asynchronous SSHv2 client and server library
description: |
    AsyncSSH is a Python package which provides an asynchronous client and server implementation of the SSHv2 protocol on top of the Python 3.6+ asyncio framework.
builddeps  :
    - python-build
    - python-installer
    - python-packaging
    - python-setuptools
rundeps    :
    - python-cryptography
    - python-typing-extensions
build      : |
    %python3_setup
install    : |
    %python3_install
