name       : libgtkmm-4
version    : 4.19.1
release    : 5
source     :
    - https://download.gnome.org/sources/gtkmm/4.19/gtkmm-4.19.1.tar.xz : 2b443ddfbf0cf28c4bece447a5bba62028c49df45ccb1b3f438a3a3e0bca31aa
homepage   : https://gtkmm.org
license    : LGPL-2.1-or-later
component  : desktop.gtk
summary    : C++ bindings to GTK+
description: |
    C++ bindings to GTK+
optimize   :
    - lto
builddeps  :
    - pkgconfig(epoxy)
    - pkgconfig(gtk4)
    - pkgconfig(pangomm-2.48)
patterns   :
    - devel : [/usr/lib64/g*]
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
