name       : python-tifffile
version    : 2025.9.9
release    : 7
source     :
    - https://files.pythonhosted.org/packages/source/t/tifffile/tifffile-2025.9.9.tar.gz : 6cf97ef548970eee9940cf8fc4203e57b4462a72e1e5e7a667ecdeb96113bc5f
homepage   : https://github.com/cgohlke/tifffile/
license    : BSD-3-Clause
component  : programming.python
summary    : Read and write TIFF files
description: |
    Tifffile is a Python library to store numpy arrays in TIFF (Tagged Image File Format) files, and read image and metadata from TIFF-like files used in bioimaging.
builddeps  :
    - python-build
    - python-installer
    - python-setuptools
rundeps    :
    - numpy
build      : |
    %python3_setup
install    : |
    %python3_install
#check      : |
#    # requires packaging python-fsspec and python-xarray
#    %python3_test pytest3 -v
