name       : python-cssselect
version    : 1.3.0
release    : 6
source     :
    - https://files.pythonhosted.org/packages/source/c/cssselect/cssselect-1.3.0.tar.gz : 57f8a99424cfab289a1b6a816a43075a4b00948c86b4dcf3ef4ee7e15f7ab0c7
homepage   : https://github.com/scrapy/cssselect
license    : BSD-3-Clause
component  : programming.python
summary    : cssselect parses CSS3 Selectors and translates them to XPath 1.0
description: |
    cssselect parses CSS3 Selectors and translate them to XPath 1.0 expressions. Such expressions can be used in lxml or another XPath engine to find the matching elements in an XML or HTML document.
builddeps  :
    - python-build
    - python-installer
    - python-setuptools
checkdeps  :
    - python-lxml
    - python-pytest
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest3 -v
