name       : gnome-backgrounds
version    : '49.0'
release    : 23
source     :
    - https://download.gnome.org/sources/gnome-backgrounds/49/gnome-backgrounds-49.0.tar.xz : 01fe260de58ba00e44aba589a998e33e8bc7aecc701df0bee64cf4cfba44f4b5
homepage   : https://gitlab.gnome.org/GNOME/gnome-backgrounds
license    :
    - CC-BY-SA-3.0
    - GPL-2.0-or-later
component  : desktop.gnome
summary    : Default GNOME artwork
description: |
    Default GNOME artwork
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
    install -m00644 $pkgfiles/*.jpg -t $installdir/usr/share/backgrounds/gnome/
