name       : python-comm
version    : 0.2.3
release    : 5
source     :
    - https://files.pythonhosted.org/packages/source/c/comm/comm-0.2.3.tar.gz : 2dc8048c10962d55d7ad693be1e7045d891b7ce8d999c97963a5e3e99c055971
homepage   : https://github.com/ipython/comm
license    : BSD-3-Clause
component  : programming.python
summary    : Python Comm implementation for the Jupyter kernel protocol
description: |
    It provides a way to register a Kernel Comm implementation, as per the Jupyter kernel protocol. It also provides a base Comm implementation and a default CommManager that can be used.
builddeps  :
    - python-build
    - python-hatchling
    - python-installer
rundeps    :
    - python-traitlets
build      : |
    %python3_setup
install    : |
    %python3_install
