name       : sayonara-player
version    : 1.9.0
release    : 12
source     :
    - https://gitlab.com/luciocarreras/sayonara-player/-/archive/1.9.0-stable1/sayonara-player-1.9.0-stable1.tar.gz : 1999f2dad21f09df65d66a860e0edff2e11d92b63626cde008bab2a9d78de5b9
homepage   : https://sayonara-player.com/
license    : GPL-3.0-or-later
component  : multimedia.audio
summary    : A small and fast audio player built with Qt
description: |
    Sayonara is a small, clear and fast audio player written in C++, supported by the Qt framework. It uses GStreamer as audio backend.
builddeps  :
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5UiTools)
    - pkgconfig(gstreamer-app-1.0)
    - pkgconfig(taglib)
setup      : |
    %cmake_ninja -DBUILD_SHARED_LIBS=true -DCMAKE_BUILD_TYPE=Release
build      : |
    %ninja_build
install    : |
    %ninja_install
