name       : ffmpegthumbs
version    : 24.12.3
release    : 90
source     :
    - https://download.kde.org/stable/release-service/24.12.3/src/ffmpegthumbs-24.12.3.tar.xz : 2d22f2342f38cb4c09c17a691ffebcf9a09b2025a501f45e688b952319c10de9
homepage   : https://kde.org/applications/multimedia/org.kde.ffmpegthumbs
license    : GPL-2.0-or-later
component  : desktop.kde
summary    : Video thumbnail generator
description: |
    FFMpegThumbs is a video thumbnail generator for KDE file managers.
builddeps  :
    - pkgconfig(Qt6Core)
    - pkgconfig(libavcodec)
    - kf6-kio-devel
clang      : yes
optimize   :
    - speed
    - thin-lto
setup      : |
    %cmake_kf6 -DBUILD_WITH_QT6=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
