name       : gnome-session
version    : '49.0'
release    : 46
source     :
    - https://download.gnome.org/sources/gnome-session/49/gnome-session-49.0.tar.xz : 5a75622e63d1b75145c9ebe67e828367a75f5ace4b6237f64e54661e6a545ef3
homepage   : https://gitlab.gnome.org/GNOME/gnome-session
license    : GPL-2.0-or-later
summary    :
    - Provides GNOME session core
    - shell : Runtime support for GNOME Shell Session.
description:
    - Provides GNOME session core
    - shell : Runtime support for GNOME Shell Session
component  :
    - desktop.gnome.core
    - shell : desktop.gnome
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(gnome-desktop-3.0)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(sm)
    - pkgconfig(upower-glib)
    - pkgconfig(xtrans)
    - pkgconfig(xtst)
    - docbook-xml
    - xmlto
rundeps    :
    - gsettings-desktop-schemas
    - gvfs
    - udisks
    - upower
    - xdg-user-dirs
    - xdg-user-dirs-gtk
    - xdg-utils
    - shell :
        - gnome-session
        - pipewire
        - xdg-desktop-portal-gnome
patterns   :
    - shell :
        - /usr/share/xdg-desktop-portal/gnome-portals.conf
        - /usr/share/xsessions
        - /usr/share/wayland-sessions
replaces   :
    - shell :
        - gnome-session-shell-experimental
setup      : |
    #patch -p1 -i $pkgfiles/0001-Fix-grep-error-for-etc-shells-on-Solus.patch
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
