name       : python-pivy
version    : 0.6.10
release    : 10
source     :
    - https://github.com/coin3d/pivy/archive/refs/tags/0.6.10.tar.gz : 7b409816c9fad84cf94f93659281f9dd2501d285eb2fc609e9401a3d004ce723
homepage   : https://github.com/coin3d/pivy
license    : ISC
component  : programming.python
summary    : Python bindings to coin3d
description: |
    Pivy is a Coin binding for Python. Coin is a high-level 3D graphics library with a C++ Application Programming Interface. Coin uses scene-graph data structures to render real-time graphics suitable for mostly all kinds of scientific and engineering visualization applications.
builddeps  :
    - pkgconfig(SoQt)
    - pkgconfig(glu)
    - pkgconfig(python3)
    - swig
rundeps    :
    - numpy
    - python-pyside6
clang      : true
setup      : |
    %cmake_ninja -DPIVY_USE_QT6=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
    %python3_compile
