name       : qutebrowser
version    : 3.4.0
release    : 48
source     :
    - https://github.com/qutebrowser/qutebrowser/releases/download/v3.4.0/qutebrowser-3.4.0.tar.gz : 814124c0ed337430e613a1da366d5e38904cb2049afb1505971456ca5ca6223e
homepage   : https://qutebrowser.org
license    : GPL-3.0-or-later
component  : network.web.browser
summary    : A keyboard-driven, vim-like browser based on PyQt6.
description: |
    A keyboard-driven, vim-like browser based on PyQt6.
builddeps  :
    - pkgconfig(python3)
    - asciidoc
rundeps    :
    - pygments
    - python-jinja
    - python-pyqt6-webengine
    - pyyaml
build      : |
    %make -f misc/Makefile
install    : |
    %make_install -f misc/Makefile PREFIX=/usr
