name       : ghex
version    : '48.1'
release    : 14
source     :
    - https://download.gnome.org/sources/ghex/48/ghex-48.1.tar.xz : 4feab8af967e2763f28bc77a4ddcf54a367aa1d85496fef0501986bd803d89f2
homepage   : https://gitlab.gnome.org/GNOME/ghex
license    :
    - GPL-2.0-or-later
    - GFDL-1.1-only
component  : desktop.gnome
summary    : GHex is a hex editor for the GNOME desktop.
description: |
    GHex can load raw data from binary files and display them for editing in a traditional hex editor view. The display is split in two columns, with hexadecimal values in one column and the ASCII representation in the other. GHex is a useful tool for working with raw data.
builddeps  :
    - pkgconfig(libadwaita-1)
    - desktop-file-utils
    - itstool
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
