name       : python-beautifulsoup4
version    : 4.13.5
release    : 25
source     :
    - https://files.pythonhosted.org/packages/source/b/beautifulsoup4/beautifulsoup4-4.13.5.tar.gz : 5e70131382930e7c3de33450a2f54a63d5e4b19386eab43a5b34d594268f3695
homepage   : https://www.crummy.com/software/BeautifulSoup/
license    : MIT
component  : programming.python
summary    : Beautiful Soup is a Python library designed for quick turnaround projects like screen-scraping (also known as BS4)
description: |
    Beautiful Soup is a Python library designed for quick turnaround projects like screen-scraping (also known as BS4).
builddeps  :
    - python-build
    - python-hatchling
    - python-installer
checkdeps  :
    - python-html5lib
    - python-lxml
    - python-pytest
    - python-soupsieve
    - python-typing-extensions
rundeps    :
    - python-soupsieve
    - python-typing-extensions
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest -v
