name       : xfce4-terminal
version    : 1.1.3
release    : 4
source     :
    - https://archive.xfce.org/src/apps/xfce4-terminal/1.1/xfce4-terminal-1.1.3.tar.bz2 : 214dd588d441b69f816009682a3bb4652cc19bed7ea64b612a12f097417b3d45
homepage   : https://docs.xfce.org/apps/xfce4-terminal/start
license    : GPL-2.0-or-later
component  : desktop.xfce
summary    : Xfce Terminal Emulator.
description: |
    Xfce Terminal Emulator.
builddeps  :
    - pkgconfig(libxfce4ui-2)
    - pkgconfig(vte-2.91)
setup      : |
    %configure --disable-debug --libexecdir=/usr/lib64/xfce4
build      : |
    %make
install    : |
    %make_install
    # Install appstream metainfo
    install -Dm00644 $pkgfiles/org.xfce.terminal.metainfo.xml -t $installdir/usr/share/metainfo
