name       : openrazer
version    : 3.9.0
release    : 337
source     :
    - https://github.com/openrazer/openrazer/archive/v3.9.0.tar.gz : 737a72e044c86586cf787fc15643a443ccea11ec5f0e78e57453c060ae26a2fa
license    : GPL-2.0-or-later
component  :
    - kernel.drivers
    - current : kernel.drivers
    - common : system.utils
    - modaliases : kernel.drivers
homepage   : https://openrazer.github.io
summary    :
    - A collection of Linux drivers for the Razer devices
    - common : Common component for openrazer kernel modules
    - current : openrazer for the linux-current kernel
    - modaliases : These files are used by the Software Center for hardware detection.
description: |
    A collection of Linux drivers for the Razer devices, providing kernel drivers, DBus services and Python bindings to interact with the DBus interface
builddeps  :
    - pkgconfig(SDL2_image)
    - pkgconfig(dbus-1)
    - pkgconfig(fftw3)
    - pkgconfig(libelf)
    - pkgconfig(udev)
    - jq
    - linux-current
    - linux-current-headers
    - linux-lts
    - linux-lts-headers
patterns   :
    - common : /*
    - main :
        - /lib64/modules/*.lts
        - /usr/lib64/modules/*.lts
    - current :
        - /lib64/modules/*.current
        - /usr/lib64/modules/*.current
    - modaliases : /usr/share/linux-driver-management/modaliases
permanent  :
    - /lib64/modules
    - /usr/usr/lib64/modules
rundeps    :
    - common :
        - numpy
        - python-daemonize
        - python-evdev
        - python-gobject
        - python-notify2
        - python-setproctitle
        - python3-dbus
        - python3-pyudev
        - xaut
        - xdotool
    - current :
        - openrazer-common
    - openrazer-common
replaces   :
    - razer-drivers
    - common : razer-drivers-common
    - current : razer-drivers-current
    - modaliases : razer-drivers-modaliases
setup      : |
    sed -i "s|depmod||g" Makefile
    pushd ../
    cp -a "openrazer-${version}" lts-build
    cp -a "openrazer-${version}" current-build
    popd
build      : |
    pushd lts-build
    KVER=%kernel_version_lts%
    %make KERNELDIR=/usr/lib64/modules/$KVER/build MODULEDIR=/usr/lib64/modules/$KVER/kernel/drivers/hid
    popd
    pushd current-build
    KVER=%kernel_version_current%
    %make KERNELDIR=/usr/lib64/modules/$KVER/build MODULEDIR=/usr/lib64/modules/$KVER/kernel/drivers/hid
    popd

    # Generate modaliases from the LTS tree
    pushd lts-build
    mkmodaliases "${package}" -o "${package}.modaliases" driver/*.ko
    popd
install    : |
    pushd lts-build
    KVER=%kernel_version_lts%
    install -d -m 00644 $installdir/usr/lib64/modules/$KVER/kernel/drivers/hid
    %make install_i_know_what_i_am_doing KERNELDIR=/usr/lib64/modules/$KVER/build MODULEDIR=/usr/lib64/modules/$KVER/kernel/drivers/hid DESTDIR=$installdir
    popd
    # Razer's build system really flops when things already exist.. Autotools wouldn't hurt.
    rm -rfv $installdir/usr/{lib,share}
    pushd current-build
    KVER=%kernel_version_current%
    install -d -m 00644 $installdir/usr/lib64/modules/$KVER/kernel/drivers/hid
    %make install_i_know_what_i_am_doing KERNELDIR=/usr/lib64/modules/$KVER/build MODULEDIR=/usr/lib64/modules/$KVER/kernel/drivers/hid DESTDIR=$installdir
    popd

    # Use example file as default configuration
    install -D -m 00644 $installdir/usr/share/openrazer/razer.conf.example $installdir/usr/share/openrazer/razer.conf

    # Now install modaliases for LDM
    install -D -m 00644 lts-build/${package}.modaliases $installdir/usr/share/linux-driver-management/modaliases/${package}.modaliases

    # Compress modules with zstd
    find "$installdir" -name '*.ko' -exec strip --strip-debug {} \; -exec zstd {} \; -exec rm -v {} \;

    # Usr-merge
    install -dm00755 $installdir/lib64
    pushd $installdir/usr
    file_list=()
    while IFS=  read -r -d $'\0'; do
        file_list+=("$REPLY")
    done < <(find lib64/modules -type f -print0)
    for file in "${file_list[@]}"; do
        parent=$(dirname "$file")
        install -dm00755 "$installdir/$parent"
        ln -srv "$installdir/usr/$file" "$installdir/$file"
    done
    popd
