name       : librest
version    : 0.10.2
release    : 15
source     :
    - https://gitlab.gnome.org/GNOME/librest/-/archive/0.10.2/librest-0.10.2.tar.gz : adef677ecdbe16f94906f59f07519938a82a207b8c019e37f2d68463f94a464d
homepage   : https://gitlab.gnome.org/GNOME/librest
license    : LGPL-2.1-or-later
component  : desktop.gnome.core
summary    : RESTful API library
description: |
    librest was designed to make it easier to access web services that claim to be "RESTful". It includes convenience wrappers for libsoup and libxml to ease remote use of the RESTful API.
emul32     : true
builddeps  :
    - pkgconfig32(gobject-2.0)
    - pkgconfig32(json-glib-1.0)
    - pkgconfig32(libsoup-3.0)
    - pkgconfig32(libxml-2.0)
setup      : |
    if [[ ! -z "${EMUL32BUILD}" ]]; then
        build_gobject="false"
    else
        build_gobject="true"
    fi
    %meson_configure -Dexamples=false -Dgtk_doc=false -Dintrospection=$build_gobject
build      : |
    %ninja_build
install    : |
    %ninja_install
