name       : ptyxis
version    : '49.0'
release    : 10
source     :
    - https://download.gnome.org/sources/ptyxis/49/ptyxis-49.0.tar.xz : 5a8fd0c43fb4568452a5d6e48dc074569ac399edc1aa032be5738b51c7201735
homepage   : https://devsuite.app/ptyxis/
license    : GPL-3.0-or-later
component  : desktop.gnome
summary    : A terminal for a container-oriented desktop
description: |
    Ptyxis is a terminal for GNOME that focuses on ease-of-use in a world of containers.
builddeps  :
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libadwaita-1)
    - pkgconfig(libportal-gtk4)
    - pkgconfig(vte-2.91)
    - desktop-file-utils
setup      : |
    %meson_configure -Dgeneric=terminal
build      : |
    %ninja_build
install    : |
    %ninja_install
