name       : gnome-connections
version    : '49.0'
release    : 6
source     :
    - https://download.gnome.org/sources/gnome-connections/49/gnome-connections-49.0.tar.xz : 3a1f9466ba54914747235fae21ec6ea326c97f6f8d0090cb99cfb0a2b24c739e
homepage   : https://apps.gnome.org/Connections/
license    : GPL-2.0-or-later
component  : desktop.gnome
summary    : View and use other desktops
description: |
    Connections allows you to connect to and use other desktops. This can be a great way to access content or software on a different desktop operating system. It can also be used as a way to provide support to users who might need help.A range of different operating systems can be connected to, including Linux and Windows desktops. You can also connect to virtual machines. Connections uses the widely supported VNC and RDP protocols, and one of these must be enabled on the desktop that you want to connect to.
optimize   :
    - lto
builddeps  :
    - pkgconfig(freerdp3)
    - pkgconfig(fuse3)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gtk-vnc-2.0)
    - pkgconfig(libhandy-1)
    - pkgconfig(libsecret-1)
    - desktop-file-utils
    - itstool
    - vala
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
