name       : python-mss
version    : 10.1.0
release    : 6
source     :
    - https://files.pythonhosted.org/packages/source/m/mss/mss-10.1.0.tar.gz : 7182baf7ee16ca569e2804028b6ab9bcbf6be5c46fc2880840f33b513b9cb4f8
homepage   : https://github.com/BoboTiG/python-mss
license    : MIT
component  : programming.python
summary    : An ultra fast cross-platform multiple screenshots module in pure Python using ctypes
description: |
    An ultra fast cross-platform multiple screenshots module in pure python using ctypes.
builddeps  :
    - python-build
    - python-hatchling
    - python-installer
build      : |
    %python3_setup
install    : |
    %python3_install
