name       : loupe
version    : '49.0'
release    : 9
source     :
    - https://download.gnome.org/sources/loupe/49/loupe-49.0.tar.xz : a2ce554e8e5e1d16b836e46f1652767db2bb3bd4f7dcaa87f2569af10b863938
homepage   : https://apps.gnome.org/Loupe/
license    : GPL-3.0-or-later
component  : desktop.gnome
summary    : GNOME's default image viewer
description: |
    An image viewer application written with GTK 4, Libadwaita and Rust. Browse through your images and inspect their metadata with:
    - Fast GPU accelerated image rendering
    - Tiled rendering for vector graphics
    - Extendable and sandboxed image decoding
    - Accessible presentation of the most important metadata.
networking : true
builddeps  :
    - pkgconfig(gtk4)
    - pkgconfig(gweather4)
    - pkgconfig(lcms2)
    - pkgconfig(libadwaita-1)
    - pkgconfig(libseccomp)
    - desktop-file-utils
    - itstool
    - rust
rundeps    :
    - glycin
    - webp-pixbuf-loader
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
