name       : python-distlib
version    : 0.4.0
release    : 12
source     :
    - https://pypi.debian.net/distlib/distlib-0.4.0.tar.gz : feec40075be03a04501a973d81f633735b4b69f98b05450592310c0f401a4e0d
homepage   : https://github.com/pypa/distlib
license    : PSF-2.0
component  : programming.python
summary    : Low-level components of distutils2/packaging
description: |
    Low-level parts of packaging/distutils2 which implement the relevant PEPs and which could be used by third-party packaging tools to achieve interoperability, enhanced with additional features for dependency resolution, package resource management and more.
networking : true # Check
builddeps  :
    - python-build
    - python-installer
    - python-setuptools
    - python-wheel
checkdeps  :
    - python-pytest
setup      : |
    rm distlib/*.exe
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    export PYTHONHASHSEED=0

    pytest_args=(
        --deselect tests/test_util.py::UtilTestCase::test_package_data # URL in test 404's
        --deselect tests/test_util.py::FileOpsTestCase::test_is_writable # Build runs as root, so /etc is unexpectedly writable
    )

    %python3_test pytest -v "${pytest_args[@]}"
