name       : showtime
version    : '49.0'
release    : 5
source     :
    - https://download.gnome.org/sources/showtime/49/showtime-49.0.tar.xz : 5abcaf97ab5e9530038282848588e8ce6c26173b7303ef6756bebdb0b20ed398
homepage   : https://apps.gnome.org/Showtime/
license    : GPL-3.0-or-later
component  : multimedia.video
summary    : Watch without distraction
description: |
    Play your favorite movies and video files without hassle. Showtime features simple playback controls that fade out of your way when you're watching, fullscreen, adjustable playback speed, multiple language and subtitle tracks, and screenshots — everything you need for a straightforward viewing experience.
builddeps  :
    - pkgconfig(libadwaita-1)
    - blueprint-compiler
    - desktop-file-utils
rundeps    :
    - gstreamer-1.0-plugins-rs
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
