name       : pymarkups
version    : 4.1.1
release    : 17
source     :
    - https://github.com/retext-project/pymarkups/archive/refs/tags/4.1.1.tar.gz : eb5d91b71f285dbda0253091d7dc0478e229ebcffbbaa1fa414daedb8d748c25
homepage   : https://github.com/retext-project/pymarkups
license    : BSD-3-Clause
component  : programming.python
summary    : Wrapper around various text markups
description: |
    This module provides a wrapper around various text markup languages. Available by default are Markdown, reStructuredText and Textile, but you can easily add your own markups.
builddeps  :
    - python-build
    - python-installer
    - python-setuptools
    - python-wheel
checkdeps  :
    - pygments
    - python-docutils
    - python-markdown-math
    - python-pytest
rundeps    :
    - python-markdown-math
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest3 -v --deselect tests/test_public_api.py::APITest::test_get_pygments_stylesheet
