name       : python-tomlkit
version    : 0.13.3
release    : 8
source     :
    - https://files.pythonhosted.org/packages/source/t/tomlkit/tomlkit-0.13.3.tar.gz : 430cf247ee57df2b94ee3fbe588e71d362a941ebb545dec29b53961d61add2a1
homepage   : https://github.com/sdispater/tomlkit
license    : MIT
component  : programming.python
summary    : Style-preserving TOML library for Python
description: |
    TOML Kit is a 1.0.0-compliant TOML library. It includes a parser that preserves all comments, indentations, whitespace and internal element ordering, and makes them accessible and editable via an intuitive API.
builddeps  :
    - python-build
    - python-installer
    - python-poetry-core
checkdeps  :
    - python-pytest
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest -v
