name       : gobject-introspection
version    : 1.86.0
release    : 45
source     :
    - https://download.gnome.org/sources/gobject-introspection/1.86/gobject-introspection-1.86.0.tar.xz : 920d1a3fcedeadc32acff95c2e203b319039dd4b4a08dd1a2dfd283d19c0b9ae
homepage   : https://gi.readthedocs.io/en/latest/
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : system.base
summary    : Generate interface introspection data for GObject libraries
description: |
    GObject Introspection is a project for providing machine readable introspection data of the API of C libraries. This introspection data can be used in several different use cases, for example automatic code generation for bindings, API verification and documentation generation.
patterns   :
    - devel :
        - /usr/bin
        - /usr/lib64/gobject-introspection/giscanner
        - /usr/share
devel      : true
optimize   :
    - lto
builddeps  :
    - pkgconfig(python3)
    - python-setuptools
rundeps    :
    - devel :
        - python-setuptools
setup      : |
    %patch -p1 -i $pkgfiles/0001-scanner-Ignore-_Complex.patch
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
