name       : gobject-introspection
version    : 1.82.0
release    : 40
source     :
    - https://download.gnome.org/sources/gobject-introspection/1.82/gobject-introspection-1.82.0.tar.xz : 0f5a4c1908424bf26bc41e9361168c363685080fbdb87a196c891c8401ca2f09
homepage   : https://wiki.gnome.org/Projects/GObjectIntrospection
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : system.base
summary    : Generate interface introspection data for GObject libraries
description: |
    GObject Introspection is a project for providing machine readable introspection data of the API of C libraries. This introspection data can be used in several different use cases, for example automatic code generation for bindings, API verification and documentation generation.
patterns   :
    - devel :
        - /usr/share/gobject-introspection-1.0
        - /usr/share/aclocal
devel      : yes
optimize   :
    - lto
builddeps  :
    - pkgconfig(python3)
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
