name       : python-dasbus
version    : 1.7
release    : 1
source     :
    - https://github.com/dasbus-project/dasbus/releases/download/v1.7/dasbus-1.7.tar.gz : a8850d841adfe8ee5f7bb9f82cf449ab9b4950dc0633897071718e0d0036b6f6
homepage   : dasbus.readthedocs.io
license    : LGPL-2.1-or-later
component  : programming.python
summary    : DBus library in Python 3
description: |
    This DBus library is written in Python 3, based on GLib and inspired by pydbus. Find out more in the documentation.
builddeps  :
    - python-build
    - python-installer
    - python-setuptools
build      : |
    %python3_setup
install    : |
    %python3_install
