name       : python-httpcore
version    : 1.0.9
release    : 5
source     :
    - https://files.pythonhosted.org/packages/source/h/httpcore/httpcore-1.0.9.tar.gz : 6e34463af53fd2ab5d807f399a9b45ea31c3dfa2276f15a2c3f00afff6e176e8
homepage   : https://www.encode.io/httpcore/
license    : BSD-3-Clause
component  : programming.python
summary    : A minimal HTTP client
description: |
    The HTTP Core package provides a minimal low-level HTTP client, which does one thing only. Sending HTTP requests.
builddeps  :
    - python-build
    - python-hatch-fancy-pypi-readme
    - python-installer
rundeps    :
    - python-anyio
    - python-certifi
    - python-h11
build      : |
    %python3_setup
install    : |
    %python3_install
