name       : libgnome-games-support
version    : 2.0.2
release    : 13
source     :
    - https://download.gnome.org/sources/libgnome-games-support/2.0/libgnome-games-support-2.0.2.tar.xz : 82bbc74f08f98b833a9b6444b8479e1bd84ded0a07425d057b45f38e8783e5bd
homepage   : https://gitlab.gnome.org/GNOME/libgnome-games-support
license    :
    - GPL-3.0-or-later
    - LGPL-3.0-or-later
component  : desktop.library
summary    : library intended for use by GNOME Games
description: |
    libgnome-games-support is a small library intended for internal use by GNOME Games, but it may be used by others.
builddeps  :
    - pkgconfig(gee-0.8)
    - pkgconfig(gio-2.0)
    - pkgconfig(gtk4)
    - vala
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
