name       : mutter
version    : '49.0'
release    : 137
source     :
    - https://download.gnome.org/sources/mutter/49/mutter-49.0.tar.xz : f10ef6ed2036673730461433e11e0be3abc7460d323b3e87093b6c3972c16335
homepage   : https://gitlab.gnome.org/GNOME/mutter
license    : GPL-2.0-or-later
component  : desktop.gnome
summary    : Gnome Shell Window Manager
description: |
    Gnome Shell compositing window manager
ccache     : false
builddeps  :
    - pkgconfig(colord)
    - pkgconfig(dri)
    - pkgconfig(glycin-2)
    - pkgconfig(gnome-desktop-4)
    - pkgconfig(gnome-settings-daemon)
    - pkgconfig(gobject-introspection-1.0)
    - pkgconfig(graphene-1.0)
    - pkgconfig(gsettings-desktop-schemas)
    - pkgconfig(gtk4)
    - pkgconfig(gudev-1.0)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(lcms2)
    - pkgconfig(libcanberra-gtk3)
    - pkgconfig(libdisplay-info)
    - pkgconfig(libei-1.0)
    - pkgconfig(libinput)
    - pkgconfig(libpipewire-0.3)
    - pkgconfig(libstartup-notification-1.0)
    - pkgconfig(libwacom)
    - pkgconfig(sm)
    - pkgconfig(upower-glib)
    - pkgconfig(wayland-eglstream)
    - pkgconfig(wayland-protocols)
    - pkgconfig(wayland-server)
    - pkgconfig(xcursor)
    - pkgconfig(xkbfile)
    - pkgconfig(xkeyboard-config)
    - pkgconfig(xorg-server)
    - pkgconfig(xtst)
    - pkgconfig(xwayland)
    - python-argcomplete
    - python-docutils
patterns   :
    - common :
        - /usr/share/GConf/gsettings/mutter-schemas.convert
        - /usr/share/glib-2.0/schemas/org.gnome.mutter*
        - /usr/share/gnome-control-center/keybindings/50-mutter-*
rundeps    :
    - devel : mesalib-devel # Internal cogl requires EGL/eglmesaext.h from mesalib-devel
    - mutter-common
setup      : |
    %meson_configure \
        -Degl_device=true \
        -Dinstalled_tests=false \
        -Dprofiler=false \
        -Dremote_desktop=true \
        -Dtests=disabled \
        -Dwayland_eglstream=true
build      : |
    %ninja_build
install    : |
    %ninja_install
