name       : amdgpu_top
version    : 0.10.1
release    : 22
source     :
    - https://github.com/Umio-Yasuno/amdgpu_top/archive/refs/tags/v0.10.1.tar.gz : 99f76632866694f2fa24f2b6e7b687d34b901fdcba28762cccd8f0a876c11765
homepage   : https://github.com/Umio-Yasuno/amdgpu_top
license    : MIT
component  : system.utils
summary    : Tool that shows AMD GPU utilization
description: |
    Tool that shows AMD GPU utilization
networking : yes
builddeps  :
    - pkgconfig(libdrm)
    - rust
setup      : |
    %cargo_fetch
build      : |
    %cargo_build --no-default-features \
                 --features "tui gui json"
install    : |
    %cargo_install
    install -Dm00644 docs/amdgpu_top.1 -t $installdir/usr/share/man/man1/
    install -Dm00644 assets/amdgpu_top.desktop -t $installdir/usr/share/applications
    install -Dm00644 $pkgfiles/io.github.umio_yasuno.amdgpu_top.metainfo.xml -t $installdir/usr/share/metainfo
