name       : taglib
version    : 2.0.2
release    : 9
source     :
    - https://github.com/taglib/taglib/releases/download/v2.0.2/taglib-2.0.2.tar.gz : 0de288d7fe34ba133199fd8512f19cc1100196826eafcb67a33b224ec3a59737
license    :
    - LGPL-2.1-or-later
    - MPL-1.1
component  : multimedia.library
homepage   : http://taglib.github.io/
summary    : Library to read metadata from a variety of multimedia formats
description: |
    TagLib is a library for reading and editing the meta-data of several popular audio formats. Currently it supports both ID3v1 and ID3v2 for MP3 files, Ogg Vorbis comments and ID3 tags and Vorbis comments in FLAC, MPC, Speex, WavPack TrueAudio, WAV, AIFF, MP4 and ASF files.
checkdeps  :
    - pkgconfig(cppunit)
    - utfcpp
clang      : yes
optimize   :
    - speed
    - thin-lto
setup      : |
    %cmake_ninja \
                 -DBUILD_SHARED_LIBS=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    %ninja_check
