name       : libgepub
version    : 0.7.3
release    : 18
source     :
    - https://download.gnome.org/sources/libgepub/0.7/libgepub-0.7.3.tar.xz : 5a56695aa8a9132d67c0792a40f252ce0a48d9d032b4e1a8a6ce98af14fd5e1b
homepage   : https://gitlab.gnome.org/GNOME/libgepub
license    : LGPL-2.0-only
component  : programming.library
summary    : Library for handling epub documents
description: |
    libgepub is a GObject based library for handling and rendering epub documents.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libarchive)
    - pkgconfig(libsoup-3.0)
    - pkgconfig(webkit2gtk-4.1)
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
