name       : gnome-tweaks
version    : '49.0'
release    : 44
source     :
    - https://download.gnome.org/sources/gnome-tweaks/49/gnome-tweaks-49.0.tar.xz : b3909bdcb4905b68427d6ab581e01f436dff8e5c0a389b1e0b14500f18806ebb
homepage   : https://gitlab.gnome.org/GNOME/gnome-tweaks
license    : GPL-3.0-or-later
component  : desktop.gnome
summary    : A tool to customize advanced GNOME 3 options
description: |
    A tool to customize advanced GNOME 3 options.
replaces   :
    - gnome-tweak-tool
builddeps  :
    - pkgconfig(gsettings-desktop-schemas)
    - pkgconfig(libadwaita-1)
    - pkgconfig(pygobject-3.0)
    - pkgconfig(python3)
    - desktop-file-utils
rundeps    :
    - python-gobject
setup      : |
    %patch -p1 -i $pkgfiles/0001-Don-t-show-extensions-notice.patch
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
