name       : gthumb
version    : 3.12.8
release    : 43
source     :
    - https://download.gnome.org/sources/gthumb/3.12/gthumb-3.12.8.tar.xz : afc74a271f6017b7581319efc8b8ab56400990ab9d200160a4efa6fcbe2274f2
homepage   : https://gitlab.gnome.org/GNOME/gthumb/
license    : GPL-2.0-or-later
component  : multimedia.graphics
summary    : Image viewer and browser utility
description: |
    gthumb is an application for viewing, editing, and organizing collections of images.
builddeps  :
    - pkgconfig(appstream)
    - pkgconfig(champlain-0.12)
    - pkgconfig(clutter-gtk-1.0)
    - pkgconfig(colord)
    - pkgconfig(exiv2)
    - pkgconfig(gsettings-desktop-schemas)
    - pkgconfig(gstreamer-plugins-base-1.0)
    - pkgconfig(libbrasero-media3)
    - pkgconfig(libheif)
    - pkgconfig(libjpeg)
    - pkgconfig(libjxl)
    - pkgconfig(libraw)
    - pkgconfig(librsvg-2.0)
    - pkgconfig(libsecret-1)
    - pkgconfig(libssh)
    - pkgconfig(libwebp)
    - pkgconfig(webkit2gtk-4.0)
    - itstool
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
