name       : python-asgiref
version    : 3.9.1
release    : 6
source     :
    - https://files.pythonhosted.org/packages/source/a/asgiref/asgiref-3.9.1.tar.gz : a5ab6582236218e5ef1648f242fd9f10626cfd4de8dc377db215d5d5098e3142
homepage   : https://github.com/django/asgiref/
license    : BSD-3-Clause
component  : programming.python
summary    : ASGI specs, helper code, and adapters
description: |
    ASGI is a standard for Python asynchronous web apps and servers to communicate with each other, and positioned as an asynchronous successor to WSGI.
builddeps  :
    - python-build
    - python-installer
    - python-setuptools
checkdeps  :
    - python-pytest-asyncio
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest -v
