name       : libadwaita
version    : 1.8.0
release    : 33
source     :
    - https://download.gnome.org/sources/libadwaita/1.8/libadwaita-1.8.0.tar.xz : 2836d2c0c0f46dcdb52f94019477f537810283c710802d8e6671efdebe2637c9
homepage   : https://gnome.pages.gitlab.gnome.org/libadwaita/
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : Building blocks for modern adaptive GNOME applications.
description: |
    Adwaita offers application developers many widgets and objects to build GNOME applications scaling from desktop workstations to mobile phones.
optimize   :
    - lto
builddeps  :
    - pkgconfig(appstream)
    - pkgconfig(gobject-introspection-1.0)
    - pkgconfig(gtk4)
    - sassc
    - vala
setup      : |
    %meson_configure -Dexamples=false
build      : |
    %ninja_build
install    : |
    %ninja_install
#check      : |
#    %ninja_check
