name       : librsvg
version    : 2.61.1
release    : 66
source     :
    - https://download.gnome.org/sources/librsvg/2.61/librsvg-2.61.1.tar.xz : bc1bbcd419120b098db28bea55335d9de2470d4e6a9f6ee97207b410fc15867d
homepage   : https://gitlab.gnome.org/GNOME/librsvg
license    :
    - LGPL-2.1-or-later
component  : desktop.library
summary    : Library to render SVG files using Cairo
description: |
    A small library to render Scalable Vector Graphics (SVG), associated with the GNOME Project. It renders SVG files to Cairo surfaces. Cairo is the 2D, antialiased drawing library that GNOME uses to draw things to the screen or to generate output for printing
optimize   : speed
networking : true
emul32     : true
patterns   :
    - devel :
        - /usr/bin
builddeps  :
    - pkgconfig32(fontconfig)
    - pkgconfig32(gdk-pixbuf-2.0)
    - pkgconfig32(libpng)
    - pkgconfig32(libxml-2.0)
    - pkgconfig32(pango)
    - pkgconfig32(xdamage)
    - pkgconfig32(xshmfence)
    - cargo-c
    - python-docutils # man
    - rust-32bit
    - vala
setup      : |
    flags='-Ddocs=disabled '
    if [ ! -z $EMUL32BUILD ]; then
        flags+='-Dtriplet=i686-unknown-linux-gnu -Dintrospection=disabled'
        pixbuf=enabled
    else
        pixbuf=disabled
    fi
    %meson_configure $flags -Dpixbuf-loader=$pixbuf
build      : |
    %ninja_build
install    : |
    %ninja_install
    rm -rf $installdir/usr/share/doc
