name       : metacity
version    : 3.57.1
release    : 21
source     :
    - https://download.gnome.org/sources/metacity/3.57/metacity-3.57.1.tar.xz : 1293a26e4dedfd4bf200b5bb788673008979ae3ac6d3053f7db481b87acc7cde
homepage   : https://gitlab.gnome.org/GNOME/metacity/
license    : GPL-2.0-or-later
component  : desktop.gnome
summary    : Window manager of GNOME Flashback.
description: |
    Window manager of GNOME Flashback.
builddeps  :
    - pkgconfig(dconf)
    - pkgconfig(gsettings-desktop-schemas)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libcanberra)
    - pkgconfig(libgtop-2.0)
    - pkgconfig(libstartup-notification-1.0)
    - pkgconfig(sm)
    - pkgconfig(xft)
    - pkgconfig(xpresent)
    - pkgconfig(xres)
setup      : |
    %patch -p1 -i $pkgfiles/0001-revert-window-stop-updating-layers.patch
    %patch -p1 -i $pkgfiles/0002-window-remove-obsolete-comments.patch
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
