name       : kasts
version    : 24.12.3
release    : 21
source     :
    - https://download.kde.org/stable/release-service/24.12.3/src/kasts-24.12.3.tar.xz : 45351ce35d2188e732544cc14b48d3589dfe5e5206884502e9695f5bdee37570
homepage   : https://apps.kde.org/kasts/
license    : GPL-2.0-or-later
component  : desktop.kde
summary    : Kasts is a convergent podcast application that looks good on desktop and mobile.
description: |
    Kasts is a convergent podcast application that looks good on desktop and mobile. Its main features are:
    - Episode management through play queue
    - Sync playback positions with other clients through gpodder.net or gpodder-nextcloud
    - Variable playback speed
    - Search for podcasts
    - Full system integration: e.g. inhibit system suspend while listening
libsplit   : no
builddeps  :
    - pkgconfig(Qt6Multimedia)
    - pkgconfig(Qt6QuickControls2)
    - pkgconfig(Qt6Svg)
    - pkgconfig(gstreamer-1.0)
    - pkgconfig(taglib)
    - pkgconfig(vlc-plugin)
    - breeze-icons-devel
    - kf6-kcolorscheme-devel
    - kf6-kconfig-devel
    - kf6-kcoreaddons-devel
    - kf6-kcrash-devel
    - kf6-ki18n-devel
    - kf6-kirigami-devel
    - kf6-syndication-devel
    - kf6-threadweaver-devel
    - qtkeychain-qt6-devel
clang      : yes
optimize   :
    - speed
    - thin-lto
setup      : |
    %patch -p1 -i $pkgfiles/upstream.patch
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install
