name       : composefs
version    : 1.0.8
release    : 1
source     :
    - https://github.com/composefs/composefs/releases/download/v1.0.8/composefs-1.0.8.tar.xz : 207384deb196198ac4764c5b42bb558f7c661494302b380afc09447678538386
homepage   : https://github.com/composefs/composefs
license    : GPL-2.0-or-later OR Apache-2.0
component  : system.utils
summary    : The reliability of disk images, the flexibility of files
description: |
    The composefs project combines several underlying Linux features to provide a very flexible mechanism to support read-only mountable filesystem trees, stacking on top of an underlying "lower" Linux filesystem.

    The key technologies composefs uses are:
    - overlayfs as the kernel interface
    - EROFS for a mountable metadata tree
    - fs-verity (optional) from the lower filesystem
builddeps  :
    - pkgconfig(fuse3)
    - go-md2man
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install

    rm $installdir/%libdir%/*.a -v
