name       : erofs-utils
version    : 1.8.3
release    : 3
source     :
    - https://git.kernel.org/pub/scm/linux/kernel/git/xiang/erofs-utils.git/snapshot/erofs-utils-1.8.3.tar.gz : 3c5cc03603ea08ba9ae5e0420eeaea5ff17ed29e2280685310356cbf25304e85
homepage   : https://erofs.docs.kernel.org/
license    : GPL-2.0-only
component  : system.utils
summary    : Utilities for working with EROFS
description: |
    Utilities for working with EROFS
builddeps  :
    - pkgconfig(fuse3)
    - pkgconfig(liblz4)
    - pkgconfig(libzstd)
clang      : yes
setup      : |
    %reconfigure --enable-fuse \
                 --enable-multithreading
build      : |
    %make
install    : |
    %make_install
