name       : python-bottle
version    : 0.13.4
release    : 15
source     :
    - https://files.pythonhosted.org/packages/source/b/bottle/bottle-0.13.4.tar.gz : 787e78327e12b227938de02248333d788cfe45987edca735f8f88e03472c3f47
homepage   : https://bottlepy.org/docs/dev/
license    : MIT
component  : programming.python
summary    : Bottle is a fast, simple and lightweight WSGI micro web-framework for Python
description: |
    Bottle is a fast, simple and lightweight WSGI micro web-framework for Python. It offers request dispatching (Routes) with url parameter support, templates, a built-in HTTP Server and adapters for many third party WSGI/HTTP-server and template engines - all in a single file and with no dependencies other than the Python Standard Library.
builddeps  :
    - python-build
    - python-installer
    - python-setuptools
checkdeps  :
    - python-pytest
setup      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest3 -k 'not test_sendfile'
