name       : gnome-weather
version    : '49.0'
release    : 31
source     :
    - https://download.gnome.org/sources/gnome-weather/49/gnome-weather-49.0.tar.xz : ee1f76b85eba9db0c8d5c02041a9d85ecdd22abb5ec6bb3ff32225929c0fce5f
homepage   : https://apps.gnome.org/Weather/
license    : GPL-2.0-or-later
component  : desktop.gnome
summary    : Show weather conditions and forecast
description: |
    A small application that allows you to monitor the current weather conditions for your city, or anywhere in the world. It provides access to detailed forecasts, up to 7 days, with hourly details for the current and next day, using various internet services. It also optionally integrates with the GNOME Shell, allowing you to see the current conditions of the most recently searched cities by just typing the name in the Activities Overview.
optimize   :
    - lto
builddeps  :
    - pkgconfig(gjs-1.0)
    - pkgconfig(gweather4)
    - pkgconfig(libadwaita-1)
    - pkgconfig(libgeoclue-2.0)
    - desktop-file-utils
    - typescript
rundeps    :
    - gjs
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
