name       : libgtksourceview5
version    : 5.18.0
release    : 13
source     :
    - https://download.gnome.org/sources/gtksourceview/5.18/gtksourceview-5.18.0.tar.xz : 051a78fe38f793328047e5bcd6d855c6425c0b480c20d9432179e356742c6ac0
homepage   : https://gitlab.gnome.org/GNOME/gtksourceview
license    : LGPL-2.1-or-later
component  : desktop.gnome.core
summary    : A text widget adding syntax highlighting and more to GNOME
description: |
    A text widget adding syntax highlighting and more to GNOME
optimize   :
    - lto
builddeps  :
    - pkgconfig(gtk4)
    - pkgconfig(libpcre2-posix)
    - pkgconfig(libxml-2.0)
    - valadoc
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
