name       : dconf-editor
version    : '49.0'
release    : 31
source     :
    - https://download.gnome.org/sources/dconf-editor/49/dconf-editor-49.0.tar.xz : 90a8ccfadf51dff31e0028324fb9a358b2d26c5ae861a71c7dbf9f4dd9bdd399
homepage   : https://apps.gnome.org/DconfEditor/
license    : GPL-3.0-or-later
component  : desktop.gnome
summary    : A graphical tool for editing the dconf database
description: |
    Dconf Editor is a tool to allow direct editing of the dconf configuration database. This is useful when developing applications that use these settings. Editing your configuration directly is an advanced feature and may cause applications to not work correctly.
builddeps  :
    - pkgconfig(dconf)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libhandy-1)
    - desktop-file-utils
    - vala
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
