name       : gnome-mines
version    : 49.0.1
release    : 24
source     :
    - https://download.gnome.org/sources/gnome-mines/49/gnome-mines-49.0.1.tar.xz : 8b0ca05c033b3c2599c992f88ebd94cb2b0c8e388ea0c02ae71db26f43f56c84
homepage   : https://gitlab.gnome.org/GNOME/gnome-mines
license    : GPL-3.0-or-later
component  : games.puzzle
summary    : Clear hidden mines from a minefield
description: |
    Mines (previously gnomine) is a puzzle game where you locate mines floating in an ocean using only your brain and a little bit of luck. You start the game with a grid of covered squares and no idea what is in them. Clicking on a square reveals what is in it: either empty ocean or a mine. If you find a mine bad things happen and the game is over. If you uncover an empty square, you survive and get to try again. We do give you a bit of help; if you find an empty piece of ocean a number is printed there telling you how many mines are in the adjacent squares (or no number if there are no nearby mines). Once you find a few clear squares you can start to deduce which squares have mines in them and which don't. You win the game once you have revealed all the un-mined squares and marked all the mined squares.
builddeps  :
    - pkgconfig(libadwaita-1)
    - pkgconfig(libgnome-games-support-2)
    - pkgconfig(librsvg-2.0)
    - desktop-file-utils
    - itstool
    - vala
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
