name       : gnome-web
version    : '49.0'
release    : 77
source     :
    - https://download.gnome.org/sources/epiphany/49/epiphany-49.0.tar.xz : 271ec735b9836b97449e32793d354a8afb6b9f8d2d3d75821885d5e155707929
homepage   : https://apps.gnome.org/Epiphany/
license    : GPL-3.0-or-later
summary    : Browse the web
description: |
    The web browser for GNOME, featuring tight integration with the desktop and a simple and intuitive user interface that allows you to focus on your web pages. If you’re looking for a simple, clean, beautiful view of the web, this is the browser for you. Web is often referred to by its code name, Epiphany.
component  : network.web.browser
optimize   :
    - lto
builddeps  :
    - pkgconfig(appstream-glib)
    - pkgconfig(gcr-4)
    - pkgconfig(gsettings-desktop-schemas)
    - pkgconfig(gstreamer-1.0)
    - pkgconfig(hogweed)
    - pkgconfig(icu-io)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libadwaita-1)
    - pkgconfig(libdazzle-1.0)
    - pkgconfig(libnotify)
    - pkgconfig(libportal-gtk4)
    - pkgconfig(libsecret-1)
    - pkgconfig(libsoup-3.0)
    - pkgconfig(libxslt)
    - pkgconfig(sqlite3)
    - pkgconfig(webkitgtk-6.0)
    - blueprint-compiler
    - desktop-file-utils
    - itstool
setup      : |
    %patch -p1 -i $pkgfiles/0001-Set-Solus-blog-as-default-homepage.patch
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
replaces   :
    - epiphany
    - dbginfo : epiphany-dbginfo
