name       : python-tzdata
version    : '2025.2'
release    : 4
source     :
    - https://files.pythonhosted.org/packages/source/t/tzdata/tzdata-2025.2.tar.gz : b60a638fcc0daffadf82fe0f57e53d06bdec2f36c4df66280ae79bce6bd6f2b9
homepage   : https://github.com/python/tzdata
license    : Apache-2.0
component  : programming.python
summary    : Python package wrapping the IANA time zone database
description: |
    This is a Python package containing zic-compiled binaries for the IANA time zone database. It is intended to be a fallback for systems that do not have system time zone data installed (or don't have it installed in a standard location), as a part of PEP 615
builddeps  :
    - python-build
    - python-installer
    - python-setuptools
    - python-wheel
build      : |
    %python3_setup
install    : |
    %python3_install
