name       : python-mistune
version    : 3.1.4
release    : 19
source     :
    - https://files.pythonhosted.org/packages/source/m/mistune/mistune-3.1.4.tar.gz : b5a7f801d389f724ec702840c11d8fc48f2b33519102fc7ee739e8177b672164
homepage   : https://github.com/lepture/mistune
license    : BSD-3-Clause
component  : programming.python
summary    : A sane Markdown parser with useful plugins and renderers
description: |
    A fast yet powerful Python Markdown parser with renderers and plugins.
builddeps  :
    - cython
    - python-build
    - python-installer
    - python-setuptools
    - python-wheel
checkdeps  :
    - python-pytest
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest -v
