name       : python-fastjsonschema
version    : 2.21.2
release    : 12
source     :
    - https://github.com/horejsek/python-fastjsonschema/archive/refs/tags/v2.21.2.tar.gz : 3757b049728580d516c0af50e11eed050c8e2c1815b221954c635bde455dcc78
homepage   : https://github.com/horejsek/python-fastjsonschema
license    : BSD-3-Clause
component  : programming.python
summary    : Fast JSON schema validator for Python
description: |
    fastjsonschema implements validation of JSON documents by JSON schema. The library implements JSON schema drafts 04, 06 and 07. The main purpose is to have a really fast implementation.
builddeps  :
    - python-setuptools
checkdeps  :
    - python-pytest-benchmark
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    # Deselect tests that are broken with pytest 8
    %python3_test pytest -vv  \
        --deselect tests/test_pattern_properties.py::test_pattern_with_escape_no_warnings \
        --deselect tests/test_string.py::test_pattern_with_escape_no_warnings

