name       : pygments
version    : 2.19.2
release    : 21
source     :
    - https://files.pythonhosted.org/packages/source/p/pygments/pygments-2.19.2.tar.gz : 636cb2477cec7f8952536970bc533bc43743542f70392ae026374600add5b887
homepage   : https://pygments.org/
license    : BSD-2-Clause
component  : programming
summary    : Pygments is a syntax highlighting package written in Python
description: |
    Pygments is a generic syntax highlighter written in Python that supports over 500 languages and text formats, for use in code hosting, forums, wikis or other applications that need to prettify source code.
builddeps  :
    - python-build
    - python-hatchling
    - python-installer
build      : |
    %python3_setup
install    : |
    %python3_install
