name       : gnome-mahjongg
version    : '49.0'
release    : 16
source     :
    - https://download.gnome.org/sources/gnome-mahjongg/49/gnome-mahjongg-49.0.tar.xz : 0fda603205c3485a1114f57ec6871bb951ed92620613981b767096e91f9142d4
homepage   : https://gitlab.gnome.org/GNOME/gnome-mahjongg/
license    : GPL-2.0-or-later
component  : games.card
summary    : Mahjongg is a solitaire (one player) version of the classic Eastern tile game, Mahjongg.
description: |
    Mahjongg is a solitaire (one player) version of the classic Eastern tile game, Mahjongg.
builddeps  :
    - pkgconfig(gtk4)
    - pkgconfig(libadwaita-1)
    - pkgconfig(librsvg-2.0)
    - desktop-file-utils
    - itstool
    - vala
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
