name       : gnome-sudoku
version    : '49.0'
release    : 28
source     :
    - https://download.gnome.org/sources/gnome-sudoku/49/gnome-sudoku-49.0.tar.xz : 0b37cde207922c9a4a8a2215e2cdfe9f32f40161d28b6027f9a6913025b50ab5
homepage   : https://gitlab.gnome.org/GNOME/gnome-sudoku/-/wikis/home
license    : GPL-3.0-or-later
component  : games.puzzle
summary    : Sudoku - The popular Japanese logic puzzle
description: |
    Sudoku is a Japanese logic game that exploded in popularity in 2005. This is a logic-based number-placement puzzle in which a 9×9 square must be filled with the correct digits.
builddeps  :
    - pkgconfig(gee-0.8)
    - pkgconfig(gtk4)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libadwaita-1)
    - pkgconfig(qqwing)
    - blueprint-compiler
    - desktop-file-utils
    - itstool
    - vala
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
