name       : snapshot
version    : '49.0'
release    : 7
source     :
    - https://download.gnome.org/sources/snapshot/49/snapshot-49.0.tar.xz : 5f96193d2919c7355745d26a1b01f23c3cb30a93c742d583ec42927c4a45ae18
homepage   : https://apps.gnome.org/Snapshot/
license    : GPL-3.0-or-later
component  : desktop.gnome
summary    : Take pictures and videos
description: |
    Take pictures and videos on your computer, tablet, or phone.
builddeps  :
    - pkgconfig(gstreamer-plugins-bad-1.0)
    - pkgconfig(lcms2)
    - pkgconfig(libadwaita-1)
    - pkgconfig(libseccomp)
    - desktop-file-utils
    - rust
rundeps    :
    - gstreamer-1.0-plugins-rs
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
