name       : python-parso
version    : 0.8.5
release    : 19
source     :
    - https://github.com/davidhalter/parso/archive/refs/tags/v0.8.5.tar.gz : 5f2cef4c80d909b45e9e93840aae9e9bddecc197137ae3cc779091f5c6a83b2d
homepage   : https://github.com/davidhalter/parso
license    :
    - MIT
    - Python-2.0
component  : programming.python
summary    : A Python Parser
description: |
    Parso is a Python parser that supports error recovery and round-trip parsing for different Python versions (in multiple Python versions). Parso is also able to list multiple syntax errors in your python file.
builddeps  :
    - pkgconfig(python3)
    - python-build
    - python-installer
    - python-setuptools
checkdeps  :
    - python-pytest
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    # Python 3.12 made changes to f-string formatting. See:
    # https://github.com/davidhalter/parso/issues/222
    %python3_test pytest -v -k 'not test_python_exception_matches'
