name       : template-glib
version    : 3.38.0
release    : 13
source     :
    - https://download.gnome.org/sources/template-glib/3.38/template-glib-3.38.0.tar.xz : 40d00dc223dcf2eb7f2ec422f7dec5a67373a0ca1101abca0f49c62f050cb312
homepage   : https://gitlab.gnome.org/GNOME/template-glib
license    : LGPL-2.1-or-later
component  : programming.library
summary    : Template-GLib is a library to help you generate text based on a template and user defined state.
description: |
    Template-GLib is a library to help you generate text based on a template and user defined state. Template-GLib does not use a language runtime, so it is safe to use from any GObject-Introspectable language.
builddeps  :
    - vala
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
